#!/usr/bin/env python3
"""make-manifest.py — the integrity script required by docs/REFERENCE-IMAGE-REQUEST.md §8a.

Walks every file under refs/ and emits, per file, the fields the request says must be
*computed* rather than typed:

    bytes, sha256, format, width, height, bit_depth, has_alpha
    bytes_per_pixel  = bytes * 8 / (width * height)
    jpeg_quality_est = estimated from the luma quantisation table, if JPEG
    exif_software, exif_datetime, xmp_present, c2pa_present
    nyq_ratio        = 2-D FFT of luminance; energy in radial frequency [0.45,0.50)
                       divided by energy in [0.20,0.45)
    upscale_test     = 2/3 box-downsample + bilinear-upsample luminance MAD
    block_score      = mean discontinuity at 8px boundaries / non-boundaries
    mean_luminance   = whole-frame mean of the 8-bit luminance plane
    block_score_rel  = block_score made exposure-relative (see EXPOSURE below)
    hud_probe_*      = measured saturated-overlay fraction in each corner box and
                       in the centre box, so `has_hud` can be an observation

EXPOSURE — why `block_score` alone is not a usable gate
-------------------------------------------------------
`block_score` is a *ratio*: mean |dI| across 8-aligned columns over mean |dI| across all
other columns. The denominator is the scene's own detail. JPEG blocking is a roughly
constant absolute discontinuity in code values, while scene detail scales with luminance
(contrast is multiplicative). So for identical encoder damage the ratio rises as the
picture gets darker, and a profile *defined by* darkness fails a threshold calibrated on
bright scenes for no reason but its exposure.

Measured, one image, one encoder, q=95 fixed, only brightness varied
(`modern/exterior_daylight/run-w3nextgen-t0007.jpg`):

    mean_luminance  105.1   52.3   31.1   18.4
    block_score     1.031  1.101  1.192  1.308     <- spread 0.277, PASS -> FAIL
    (bs - 1) * L      3.22   5.28   5.95   5.66     <- very nearly constant

The excess above 1 is inversely proportional to mean luminance, so the confound divides
out exactly:

    block_score_rel = 1 + (block_score - 1) * (mean_luminance / 128)

    block_score_rel 1.025  1.041  1.047  1.044     <- spread 0.019, ~15x reduction

128 is mid-grey of the 8-bit range: a principled anchor, not a fit. `block_score_rel` is
therefore read as *the block_score this frame would have shown had it been exposed at
mid-grey*. A lossless PNG control at the same four exposures scores 0.989 / 0.997 / 0.999 /
1.000, so the null stays exposure-independent; and a quality sweep still discriminates
(bright q95/85/70/50/30 -> 1.025/1.144/1.291/1.456/1.706; the same sweep at x0.18
brightness -> 1.044/1.118/1.222/1.340/1.578, i.e. the two curves now agree instead of
diverging by 0.6). Proposed as amendment A9; `block_score` itself is kept unchanged
alongside it so the change is auditable and so no earlier verdict is silently rewritten.

It writes `_computed.json` next to itself. `MANIFEST.json` is `_computed.json` joined, by
path, with the hand-authored provenance block in `_provenance.json` (source URL, game,
depicts, identified_by, vanilla tests, ...). The split exists so a re-run can never
silently overwrite a human judgement with a machine guess, and so the numeric fields can
never be hand-edited.

Pure standard library + Pillow. No numpy in this container, so the FFT is a plain
recursive-free iterative radix-2 over a 256x256 luminance crop; that is fast enough for a
set this size and exact enough for a band ratio.

    python3 make-manifest.py            # rewrite _computed.json and MANIFEST.json
    python3 make-manifest.py --check    # recompute and diff, exit 1 on drift
"""
import cmath
import hashlib
import json
import os
import sys

from PIL import Image, ImageChops, ImageStat

HERE = os.path.dirname(os.path.abspath(__file__))
SKIP_DIRS = {
    'anti',                    # generated by our own harness; never touch it
    '__pycache__',             # interpreter output is not reference media
}
SKIP_EXT = {'.md', '.json', '.py', '.mjs', '.txt'}
# Non-image reference assets. REF-A12 (the Morrowind UI) is filled by OpenMW's MyGUI layout
# and skin definitions rather than by a screenshot, because no vanilla UI capture was
# obtainable; see refs/morrowind/REF-A12/README.md. These carry bytes and sha256 like any
# other file, and every pixel statistic is null - they are text, and a null is the honest
# value. `pixel_metrics_valid` on their provenance records is false, so §3's floors and every
# metrics population exclude them automatically.
TEXT_EXT = {'.xml', '.layout', '.skin', '.cfg', '.lua', '.csv', '.ini'}
N = 256                        # FFT crop size


# ----------------------------------------------------------------- FFT (iterative radix-2)
def fft1(a):
    n = len(a)
    j = 0
    a = list(a)
    for i in range(1, n):
        bit = n >> 1
        while j & bit:
            j ^= bit
            bit >>= 1
        j |= bit
        if i < j:
            a[i], a[j] = a[j], a[i]
    length = 2
    while length <= n:
        ang = -2 * cmath.pi / length
        wl = cmath.exp(1j * ang)
        for i in range(0, n, length):
            w = 1 + 0j
            half = length >> 1
            for k in range(half):
                u = a[i + k]
                v = a[i + k + half] * w
                a[i + k] = u + v
                a[i + k + half] = u - v
                w *= wl
        length <<= 1
    return a


def fft2_power(plane):
    """plane: list of N rows of N floats -> N x N power spectrum, DC at [0][0]."""
    rows = [fft1(r) for r in plane]
    cols = []
    for x in range(N):
        col = fft1([rows[y][x] for y in range(N)])
        cols.append(col)
    # cols[x][y]
    return [[abs(cols[x][y]) ** 2 for x in range(N)] for y in range(N)]


def hann(n):
    return [0.5 - 0.5 * cmath.cos(2 * cmath.pi * i / (n - 1)).real for i in range(n)]


def luma_crop(im):
    """Centre NxN luminance crop, Hann-windowed, mean removed."""
    g = im.convert('L')
    w, h = g.size
    if w < N or h < N:
        g = g.resize((max(N, w), max(N, h)), Image.LANCZOS)
        w, h = g.size
    left, top = (w - N) // 2, (h - N) // 2
    g = g.crop((left, top, left + N, top + N))
    px = list(g.getdata())
    win = hann(N)
    mean = sum(px) / len(px) / 255.0
    plane = []
    for y in range(N):
        row = [((px[y * N + x] / 255.0) - mean) * win[x] * win[y] for x in range(N)]
        plane.append(row)
    return plane


def radial_bands(P):
    """Sum power into normalised radial frequency bands (0 .. 0.5 cyc/px)."""
    bands = {'low': 0.0, 'mid': 0.0, 'high': 0.0, 'nyq': 0.0}
    for y in range(N):
        fy = (y if y <= N // 2 else y - N) / N
        for x in range(N):
            fx = (x if x <= N // 2 else x - N) / N
            f = (fx * fx + fy * fy) ** 0.5
            if f < 0.004:
                continue
            if f < 0.05:
                bands['low'] += P[y][x]
            elif f < 0.20:
                bands['mid'] += P[y][x]
            elif f < 0.45:
                bands['high'] += P[y][x]
            elif f <= 0.5:
                bands['nyq'] += P[y][x]
    return bands


def block_score(im):
    """Aligned/non-aligned gradient ratio specified by the acquisition request."""
    g = im.convert('L')
    w, h = g.size
    px = g.load()
    aligned = other = 0.0
    n_aligned = n_other = 0
    for y in range(h):
        for x in range(1, w):
            d = abs(px[x, y] - px[x - 1, y])
            if x % 8 == 0:
                aligned += d; n_aligned += 1
            else:
                other += d; n_other += 1
    if not n_aligned or not n_other or other == 0:
        return None
    return round((aligned / n_aligned) / (other / n_other), 6)


L_REF = 128.0          # mid-grey of the 8-bit range; the exposure block_score_rel reports at
L_FLOOR = 16.0         # below this the normalisation would divide a real fault away


def block_score_rel(bs, mean_lum):
    """`block_score` restated at a reference exposure. See EXPOSURE in the module docstring.

    Guard: a near-black frame has almost no detail in the denominator, so the raw ratio can
    be large for reasons that are not encoder damage *and* the normalisation would shrink a
    genuine fault to nothing. Luminance is therefore clamped at L_FLOOR, which makes the
    metric conservative (it under-corrects) rather than blind at the dark end.
    """
    if bs is None or mean_lum is None:
        return None
    return round(1.0 + (bs - 1.0) * (max(mean_lum, L_FLOOR) / L_REF), 6)


# ------------------------------------------------------------------- HUD / overlay probes
# `has_hud` was a folder constant in three folders and the critic measured 29 of 93 souls
# frames with literally no HUD. This makes it an observation. The rule is the critic's:
# the fraction of pixels that are both strongly chromatic and not dark
# (max-min > 55 and max > 70), inside a box. Their box was the DS3 HP-bar corner; all four
# corners plus the centre are probed here so the same field works for other games' layouts
# and so A1 clause 4 (a menu covering the *centre*) is separable from an edge HUD.
HUD_SAT_DELTA = 55
HUD_SAT_MAX = 70
HUD_THRESHOLD = 0.012          # critic's calibration: below this there is no HUD
HUD_BOXES = {
    'tl': (0.03, 0.03, 0.35, 0.13),
    'tr': (0.65, 0.03, 0.97, 0.13),
    'bl': (0.03, 0.87, 0.35, 0.97),
    'br': (0.65, 0.87, 0.97, 0.97),
    'centre': (0.30, 0.30, 0.70, 0.70),
}


def hud_probes(im):
    """Per-box fraction of strongly-chromatic, not-dark pixels. ImageChops so it runs in C:
    the arithmetic is exactly the per-pixel rule above, not an approximation of it."""
    r, g, b = im.convert('RGB').split()
    mx = ImageChops.lighter(ImageChops.lighter(r, g), b)
    mn = ImageChops.darker(ImageChops.darker(r, g), b)
    chroma = ImageChops.subtract(mx, mn)
    hot = ImageChops.multiply(
        chroma.point(lambda v: 255 if v > HUD_SAT_DELTA else 0),
        mx.point(lambda v: 255 if v > HUD_SAT_MAX else 0),
    )
    w, h = hot.size
    out = {}
    for name, (x0, y0, x1, y1) in HUD_BOXES.items():
        left, top = int(x0 * w), int(y0 * h)
        right, bottom = max(int(x1 * w), left + 1), max(int(y1 * h), top + 1)
        box = hot.crop((left, top, right, bottom))
        n = (right - left) * (bottom - top)
        out[name] = round(box.histogram()[255] / n, 6) if n else None
    return out


def upscale_test(im):
    """Mean absolute luminance difference after the specified resampling round trip."""
    g = im.convert('L')
    w, h = g.size
    small = g.resize((max(1, round(w * 2 / 3)), max(1, round(h * 2 / 3))), Image.Resampling.BOX)
    restored = small.resize((w, h), Image.Resampling.BILINEAR)
    a, b = g.tobytes(), restored.tobytes()
    return round(sum(abs(x - y) for x, y in zip(a, b)) / (len(a) * 255.0), 6)


JPEG_STD_LUMA = [16, 11, 10, 16, 24, 40, 51, 61, 12, 12, 14, 19, 26, 58, 60, 55,
                 14, 13, 16, 24, 40, 57, 69, 56, 14, 17, 22, 29, 51, 87, 80, 62,
                 18, 22, 37, 56, 68, 109, 103, 77, 24, 35, 55, 64, 81, 104, 113, 92,
                 49, 64, 78, 87, 103, 121, 120, 101, 72, 92, 95, 98, 112, 100, 103, 99]


def jpeg_quality_est(im):
    q = getattr(im, 'quantization', None)
    if not q or 0 not in q:
        return None
    tbl = list(q[0])
    if len(tbl) < 64:
        return None
    ratios = [tbl[i] / JPEG_STD_LUMA[i] for i in range(64) if JPEG_STD_LUMA[i]]
    s = sum(ratios) / len(ratios) * 100.0
    quality = (200.0 - s) / 2.0 if s > 100 else 5000.0 / s if s else 100.0
    return round(max(1.0, min(100.0, quality)), 1)


def analyse_text(path):
    """A non-image reference asset. Record identity; compute no pixel statistic."""
    raw = open(path, 'rb').read()
    return {
        'bytes': len(raw),
        'sha256': hashlib.sha256(raw).hexdigest(),
        'format': os.path.splitext(path)[1].lower().lstrip('.'),
        'asset_kind': 'text',
        'lines': raw.count(b'\n') + (1 if raw and not raw.endswith(b'\n') else 0),
        'width': None, 'height': None, 'bit_depth': None, 'has_alpha': None,
        'bytes_per_pixel': None, 'jpeg_quality_est': None,
        'exif_software': 'none', 'exif_datetime': None,
        'xmp_present': False, 'c2pa_present': False,
        'nyq_ratio': None, 'hf_ratio': None, 'upscale_test': None, 'block_score': None,
        'mean_luminance': None, 'block_score_rel': None,
        'hud_probe': None, 'hud_probe_edge_max': None, 'has_hud_measured': None,
        'ui_overlay_kind': 'none',
        'frames': None, 'animated': False,
    }


def analyse(path):
    raw = open(path, 'rb').read()
    im = Image.open(path)
    w, h = im.size
    rec = {
        'bytes': len(raw),
        'sha256': hashlib.sha256(raw).hexdigest(),
        'format': (im.format or '').lower(),
        'width': w, 'height': h,
        'bit_depth': 8 if im.mode in ('L', 'RGB', 'RGBA', 'P') else None,
        'has_alpha': im.mode in ('RGBA', 'LA') or 'transparency' in im.info,
        'bytes_per_pixel': round(len(raw) * 8 / (w * h), 4),
        'jpeg_quality_est': jpeg_quality_est(im),
        'exif_software': 'none', 'exif_datetime': None,
        'xmp_present': b'<x:xmpmeta' in raw[:200000] or b'http://ns.adobe.com/xap/' in raw[:200000],
        'c2pa_present': b'c2pa' in raw[:400000] or b'jumbf' in raw[:400000],
    }
    try:
        ex = im.getexif()
        if ex:
            rec['exif_software'] = str(ex.get(305, 'none'))
            rec['exif_datetime'] = str(ex.get(306)) if ex.get(306) else None
    except Exception:
        pass

    # Animated media (the A5 wiki GIFs, the cut video clips) are frame sequences, not
    # pictures. A5 rule 3 already sets pixel_metrics_valid false on the whole axis, so the
    # still-image battery is not merely unnecessary here, it is meaningless: it would be
    # computed off frame 0. Record identity, geometry and the sequence length; leave the
    # rest null, which is the honest value.
    n_frames = int(getattr(im, 'n_frames', 1) or 1)
    rec['frames'] = n_frames
    rec['animated'] = n_frames > 1
    if rec['animated']:
        rec.update({
            'nyq_ratio': None, 'hf_ratio': None, 'upscale_test': None, 'block_score': None,
            'mean_luminance': None, 'block_score_rel': None,
            'hud_probe': None, 'hud_probe_edge_max': None, 'has_hud_measured': None,
            'ui_overlay_kind': 'not-measured-animated',
        })
        return rec

    P = fft2_power(luma_crop(im))
    b = radial_bands(P)
    denom = b['low'] + b['mid'] + b['high']
    rec['nyq_ratio'] = round(b['nyq'] / b['high'], 6) if b['high'] else None
    rec['hf_ratio'] = round(b['high'] / denom, 6) if denom else None
    rec['upscale_test'] = upscale_test(im)
    rec['block_score'] = block_score(im)

    rec['mean_luminance'] = round(ImageStat.Stat(im.convert('L')).mean[0], 4)
    rec['block_score_rel'] = block_score_rel(rec['block_score'], rec['mean_luminance'])

    probe = hud_probes(im)
    rec['hud_probe'] = probe
    edge = [v for k, v in probe.items() if k != 'centre' and v is not None]
    rec['hud_probe_edge_max'] = round(max(edge), 6) if edge else None
    edge_hud = rec['hud_probe_edge_max'] is not None and rec['hud_probe_edge_max'] >= HUD_THRESHOLD
    centre_ui = probe.get('centre') is not None and probe['centre'] >= HUD_THRESHOLD
    rec['has_hud_measured'] = bool(edge_hud)
    rec['ui_overlay_kind'] = ('both' if edge_hud and centre_ui else
                              'edge-hud' if edge_hud else
                              'centre-ui' if centre_ui else 'none')
    return rec


# --------------------------------------------------------------- metrics validity, by purpose
# `pixel_metrics_valid` conflated two different questions: "may this file set a [p10,p90]
# fidelity band?" and "may this file be measured for art direction?". A7's dispersion
# computation is an art-direction measurement over files that are all
# `pixel_metrics_valid: false`, so with one flag its input set is either empty or the whole
# corpus. `metrics_valid_for` is a list, computed here at join time from the provenance
# judgement plus the measured numbers, so every measurement has a defined population.
#
#   fidelity-bands   M1-M12, [p10,p90] calibration. The strictest gate.
#   dispersion       A7 inter/intra-region centroids. Uses edge density and colour entropy,
#                    which JPEG blocking corrupts, so it carries its own encode gate --
#                    laxer than fidelity (it is a between-group comparison, not an absolute
#                    band) but not absent.
#   art-direction    palette, luminance distribution, sky fraction, silhouette. Robust to
#                    mild blocking; needs a full frame, so superseded crops are excluded.
#   ui-fidelity      RI-UIX06 F17-F19 glyph raster / scaling / compositing.
#   behaviour        A5. Pose, timing, framing geometry. Never a fidelity or art input.
#   subject-reference  A6. What the land and its species look like. Cited by no critic.
BLOCK_REL_FIDELITY = 1.15      # amendment A9; was an absolute 1.15 on the raw block_score
BLOCK_REL_DISPERSION = 1.30
JPEG_Q_FLOOR = 80.0


def metrics_valid_for(rel, prov, comp):
    """Which measurements this file is a legitimate input to. Computed, never typed."""
    out = []
    side = prov.get('side')
    animated = bool(comp.get('animated'))
    superseded = bool(prov.get('superseded_by'))
    brel = comp.get('block_score_rel')
    jq = comp.get('jpeg_quality_est')
    # An encode gate that is exposure-independent by construction: block_score_rel, plus
    # the two fields that were always exposure-independent and that F13 showed already say
    # these files are fine (median jpeg_quality_est is 100.0 in every Steam folder).
    encode_ok_fidelity = ((brel is None or brel <= BLOCK_REL_FIDELITY)
                          and (jq is None or jq >= JPEG_Q_FLOOR))
    encode_ok_dispersion = ((brel is None or brel <= BLOCK_REL_DISPERSION)
                            and (jq is None or jq >= JPEG_Q_FLOOR))
    forbidden = set(prov.get('forbidden_for') or [])

    if (prov.get('pixel_metrics_valid') and not animated and not superseded
            and 'fidelity-bands' not in forbidden and encode_ok_fidelity):
        out.append('fidelity-bands')

    if side in ('morrowind-art', 'morrowind-art-direction') and not superseded and not animated:
        if 'art-direction-judgement' not in forbidden:
            out.append('art-direction')
            if prov.get('a21_member') and encode_ok_dispersion:
                out.append('dispersion')

    if prov.get('slot') in ('REF-A12b', 'REF-M22') or (rel.startswith('modern/ui/')):
        out.append('ui-fidelity')

    if side in ('souls-behaviour', 'video'):
        out.append('behaviour')

    if side == 'subject-reference':
        out.append('subject-reference')

    return out


# ------------------------------------------------------------------- acquisition state
# H6: one flag (`_local`) was doing three jobs -- "on disk but not re-fetchable verbatim",
# "catalogued but deliberately not vendored", and "documentation-only id record" -- so
# `acquire.py --check`'s pass count could not distinguish a file that is present and
# verifying from one that was never downloaded.
def acquisition_state(rel, prov, on_disk):
    if prov.get('acquisition_state'):
        return prov['acquisition_state']
    fetchable = all(k in prov for k in ('source_url', 'expected_bytes', 'expected_sha256'))
    if not on_disk:
        return 'catalogued-not-vendored'
    if fetchable and not prov.get('_local'):
        return 'vendored-verifying'
    return 'vendored-local-derived'


def walk():
    out = {}
    for root, dirs, files in os.walk(HERE):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in sorted(files):
            ext = os.path.splitext(f)[1].lower()
            if ext in SKIP_EXT or f.startswith('.'):
                continue
            p = os.path.join(root, f)
            rel = os.path.relpath(p, HERE)
            try:
                out[rel] = analyse_text(p) if ext in TEXT_EXT else analyse(p)
            except Exception as e:            # noqa: BLE001 - report, never crash the walk
                out[rel] = {'error': f'{type(e).__name__}: {e}'}
            print(rel, file=sys.stderr)
    return out


def main():
    computed = walk()
    cpath = os.path.join(HERE, '_computed.json')
    if '--check' in sys.argv:
        old = json.load(open(cpath)) if os.path.exists(cpath) else {}
        # Compare complete records, not only hashes: changing an algorithm must make
        # --check fail even when the underlying media bytes are unchanged.
        drift = [k for k in set(old) | set(computed) if old.get(k) != computed.get(k)]
        if drift:
            print('DRIFT:', *drift, sep='\n  ')
            return 1
        print('ok: %d files, no drift' % len(computed))
        return 0
    json.dump(computed, open(cpath, 'w'), indent=1, sort_keys=True)

    ppath = os.path.join(HERE, '_provenance.json')
    prov = json.load(open(ppath)) if os.path.exists(ppath) else {}
    records = []
    for rel in sorted(computed):
        rec = {'path': rel}
        p = prov.get(rel, {'PROVENANCE_MISSING': True})
        rec.update(p)
        rec.update(computed[rel])
        rec['metrics_valid_for'] = metrics_valid_for(rel, p, computed[rel])
        rec['acquisition_state'] = acquisition_state(rel, p, True)
        records.append(rec)

    # Records that describe a file we deliberately did not vendor (a 3.17 GB longplay we cut
    # two clips from, an oversized wiki GIF). They are catalogued so the source is not lost;
    # they are NOT media on disk and must never be counted as coverage.
    catalogued = []
    for rel, p in sorted(prov.items()):
        if rel in computed or '/' not in rel:
            continue
        if os.path.exists(os.path.join(HERE, rel)):
            continue
        rec = {'path': rel}
        rec.update(p)
        rec['acquisition_state'] = acquisition_state(rel, p, False)
        rec['metrics_valid_for'] = []
        catalogued.append(rec)

    tally = {}
    for rec in records:
        for purpose in rec['metrics_valid_for']:
            tally[purpose] = tally.get(purpose, 0) + 1
    superseded = sum(1 for r in records if r.get('superseded_by'))
    animated = sum(1 for r in records if r.get('animated'))

    json.dump({
        'schema': 'elder-souls/reference-manifest@2',
        'spec': 'docs/REFERENCE-IMAGE-REQUEST.md §9, as amended by ACQUISITION-SPEC-AMENDMENTS.md',
        'note': 'Numeric fields come from make-manifest.py. Provenance fields come from '
                '_provenance.json and were entered by the acquiring agent. '
                'metrics_valid_for and acquisition_state are derived at join time and are '
                'not hand-editable.',
        'count': len(records),
        'counts': {
            'files_on_disk': len(records),
            'animated_sequences': animated,
            'superseded_crops_excluded_from_coverage': superseded,
            'countable_media': len(records) - superseded,
            'catalogued_not_vendored': len(catalogued),
            'by_metrics_purpose': tally,
        },
        'counts_note': 'files_on_disk is not a coverage number. Superseded crops are files '
                       'but not references (amendment ruling 5b#2), and every measurement '
                       'has its own population under by_metrics_purpose. Quote those.',
        'records': records,
        'catalogued_not_vendored': catalogued,
    }, open(os.path.join(HERE, 'MANIFEST.json'), 'w'), indent=1)
    print('wrote MANIFEST.json (%d on disk, %d catalogued-not-vendored)'
          % (len(records), len(catalogued)))
    print('metrics_valid_for:', json.dumps(tally, sort_keys=True))
    return 0


if __name__ == '__main__':
    sys.exit(main())
