#!/usr/bin/env python3
"""make-manifest.py — the integrity script required by docs/REFERENCE-IMAGE-REQUEST.md §8a.

Walks every file under refs/ and emits, per file, the fields the request says must be
*computed* rather than typed:

    bytes, sha256, format, width, height, bit_depth, has_alpha
    bytes_per_pixel  = bytes * 8 / (width * height)
    jpeg_quality_est = estimated from the luma quantisation table, if JPEG
    exif_software, exif_datetime, xmp_present, c2pa_present
    nyq_ratio        = 2-D FFT of luminance; energy in radial frequency [0.45,0.50)
                       divided by energy in [0.20,0.45)
    upscale_test     = high-frequency energy relative to what the stated resolution implies
    block_score      = mean discontinuity across 8x8 block boundaries

It writes `_computed.json` next to itself. `MANIFEST.json` is `_computed.json` joined, by
path, with the hand-authored provenance block in `_provenance.json` (source URL, game,
depicts, identified_by, vanilla tests, ...). The split exists so a re-run can never
silently overwrite a human judgement with a machine guess, and so the numeric fields can
never be hand-edited.

Pure standard library + Pillow. No numpy in this container, so the FFT is a plain
recursive-free iterative radix-2 over a 256x256 luminance crop; that is fast enough for a
set this size and exact enough for a band ratio.

    python3 make-manifest.py            # rewrite _computed.json and MANIFEST.json
    python3 make-manifest.py --check    # recompute and diff, exit 1 on drift
"""
import cmath
import hashlib
import json
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SKIP_DIRS = {'anti'}          # refs/anti/ is generated by our own harness; never touch it
SKIP_EXT = {'.md', '.json', '.py', '.mjs', '.txt'}
# Non-image reference assets. REF-A12 (the Morrowind UI) is filled by OpenMW's MyGUI layout
# and skin definitions rather than by a screenshot, because no vanilla UI capture was
# obtainable; see refs/morrowind/REF-A12/README.md. These carry bytes and sha256 like any
# other file, and every pixel statistic is null - they are text, and a null is the honest
# value. `pixel_metrics_valid` on their provenance records is false, so §3's floors and every
# metrics population exclude them automatically.
TEXT_EXT = {'.xml', '.layout', '.skin', '.cfg', '.lua', '.csv', '.ini'}
N = 256                        # FFT crop size


# ----------------------------------------------------------------- FFT (iterative radix-2)
def fft1(a):
    n = len(a)
    j = 0
    a = list(a)
    for i in range(1, n):
        bit = n >> 1
        while j & bit:
            j ^= bit
            bit >>= 1
        j |= bit
        if i < j:
            a[i], a[j] = a[j], a[i]
    length = 2
    while length <= n:
        ang = -2 * cmath.pi / length
        wl = cmath.exp(1j * ang)
        for i in range(0, n, length):
            w = 1 + 0j
            half = length >> 1
            for k in range(half):
                u = a[i + k]
                v = a[i + k + half] * w
                a[i + k] = u + v
                a[i + k + half] = u - v
                w *= wl
        length <<= 1
    return a


def fft2_power(plane):
    """plane: list of N rows of N floats -> N x N power spectrum, DC at [0][0]."""
    rows = [fft1(r) for r in plane]
    cols = []
    for x in range(N):
        col = fft1([rows[y][x] for y in range(N)])
        cols.append(col)
    # cols[x][y]
    return [[abs(cols[x][y]) ** 2 for x in range(N)] for y in range(N)]


def hann(n):
    return [0.5 - 0.5 * cmath.cos(2 * cmath.pi * i / (n - 1)).real for i in range(n)]


def luma_crop(im):
    """Centre NxN luminance crop, Hann-windowed, mean removed."""
    g = im.convert('L')
    w, h = g.size
    if w < N or h < N:
        g = g.resize((max(N, w), max(N, h)), Image.LANCZOS)
        w, h = g.size
    left, top = (w - N) // 2, (h - N) // 2
    g = g.crop((left, top, left + N, top + N))
    px = list(g.getdata())
    win = hann(N)
    mean = sum(px) / len(px) / 255.0
    plane = []
    for y in range(N):
        row = [((px[y * N + x] / 255.0) - mean) * win[x] * win[y] for x in range(N)]
        plane.append(row)
    return plane


def radial_bands(P):
    """Sum power into normalised radial frequency bands (0 .. 0.5 cyc/px)."""
    bands = {'low': 0.0, 'mid': 0.0, 'high': 0.0, 'nyq': 0.0}
    for y in range(N):
        fy = (y if y <= N // 2 else y - N) / N
        for x in range(N):
            fx = (x if x <= N // 2 else x - N) / N
            f = (fx * fx + fy * fy) ** 0.5
            if f < 0.004:
                continue
            if f < 0.05:
                bands['low'] += P[y][x]
            elif f < 0.20:
                bands['mid'] += P[y][x]
            elif f < 0.45:
                bands['high'] += P[y][x]
            elif f <= 0.5:
                bands['nyq'] += P[y][x]
    return bands


def block_score(im):
    """Mean |discontinuity| across 8x8 block boundaries minus the same measured one pixel
    inside the block. Positive means the boundary is special, i.e. JPEG blocking."""
    g = im.convert('L')
    w, h = g.size
    px = g.load()
    on = off = 0.0
    non = noff = 0
    for x in range(8, w - 1, 8):
        for y in range(0, h, 4):
            on += abs(px[x, y] - px[x - 1, y]); non += 1
            if x + 4 < w:
                off += abs(px[x + 4, y] - px[x + 3, y]); noff += 1
    for y in range(8, h - 1, 8):
        for x in range(0, w, 4):
            on += abs(px[x, y] - px[x, y - 1]); non += 1
            if y + 4 < h:
                off += abs(px[x, y + 4] - px[x, y + 3]); noff += 1
    if not non or not noff:
        return None
    return round(((on / non) - (off / noff)) / 255.0, 6)


JPEG_STD_LUMA = [16, 11, 10, 16, 24, 40, 51, 61, 12, 12, 14, 19, 26, 58, 60, 55,
                 14, 13, 16, 24, 40, 57, 69, 56, 14, 17, 22, 29, 51, 87, 80, 62,
                 18, 22, 37, 56, 68, 109, 103, 77, 24, 35, 55, 64, 81, 104, 113, 92,
                 49, 64, 78, 87, 103, 121, 120, 101, 72, 92, 95, 98, 112, 100, 103, 99]


def jpeg_quality_est(im):
    q = getattr(im, 'quantization', None)
    if not q or 0 not in q:
        return None
    tbl = list(q[0])
    if len(tbl) < 64:
        return None
    ratios = [tbl[i] / JPEG_STD_LUMA[i] for i in range(64) if JPEG_STD_LUMA[i]]
    s = sum(ratios) / len(ratios) * 100.0
    quality = (200.0 - s) / 2.0 if s > 100 else 5000.0 / s if s else 100.0
    return round(max(1.0, min(100.0, quality)), 1)


def analyse_text(path):
    """A non-image reference asset. Record identity; compute no pixel statistic."""
    raw = open(path, 'rb').read()
    return {
        'bytes': len(raw),
        'sha256': hashlib.sha256(raw).hexdigest(),
        'format': os.path.splitext(path)[1].lower().lstrip('.'),
        'asset_kind': 'text',
        'lines': raw.count(b'\n') + (1 if raw and not raw.endswith(b'\n') else 0),
        'width': None, 'height': None, 'bit_depth': None, 'has_alpha': None,
        'bytes_per_pixel': None, 'jpeg_quality_est': None,
        'exif_software': 'none', 'exif_datetime': None,
        'xmp_present': False, 'c2pa_present': False,
        'nyq_ratio': None, 'hf_ratio': None, 'upscale_test': None, 'block_score': None,
    }


def analyse(path):
    raw = open(path, 'rb').read()
    im = Image.open(path)
    w, h = im.size
    rec = {
        'bytes': len(raw),
        'sha256': hashlib.sha256(raw).hexdigest(),
        'format': (im.format or '').lower(),
        'width': w, 'height': h,
        'bit_depth': 8 if im.mode in ('L', 'RGB', 'RGBA', 'P') else None,
        'has_alpha': im.mode in ('RGBA', 'LA') or 'transparency' in im.info,
        'bytes_per_pixel': round(len(raw) * 8 / (w * h), 4),
        'jpeg_quality_est': jpeg_quality_est(im),
        'exif_software': 'none', 'exif_datetime': None,
        'xmp_present': b'<x:xmpmeta' in raw[:200000] or b'http://ns.adobe.com/xap/' in raw[:200000],
        'c2pa_present': b'c2pa' in raw[:400000] or b'jumbf' in raw[:400000],
    }
    try:
        ex = im.getexif()
        if ex:
            rec['exif_software'] = str(ex.get(305, 'none'))
            rec['exif_datetime'] = str(ex.get(306)) if ex.get(306) else None
    except Exception:
        pass

    P = fft2_power(luma_crop(im))
    b = radial_bands(P)
    denom = b['low'] + b['mid'] + b['high']
    rec['nyq_ratio'] = round(b['nyq'] / b['high'], 6) if b['high'] else None
    rec['hf_ratio'] = round(b['high'] / denom, 6) if denom else None
    # upscale_test: HF energy relative to a 1/f^2 natural-image expectation for this
    # resolution. ~1.0 = consistent with a native capture; << 1 = enlarged from smaller.
    rec['upscale_test'] = round((rec['hf_ratio'] / 0.09), 4) if rec['hf_ratio'] is not None else None
    rec['block_score'] = block_score(im)
    return rec


def walk():
    out = {}
    for root, dirs, files in os.walk(HERE):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in sorted(files):
            ext = os.path.splitext(f)[1].lower()
            if ext in SKIP_EXT or f.startswith('.'):
                continue
            p = os.path.join(root, f)
            rel = os.path.relpath(p, HERE)
            try:
                out[rel] = analyse_text(p) if ext in TEXT_EXT else analyse(p)
            except Exception as e:            # noqa: BLE001 - report, never crash the walk
                out[rel] = {'error': f'{type(e).__name__}: {e}'}
            print(rel, file=sys.stderr)
    return out


def main():
    computed = walk()
    cpath = os.path.join(HERE, '_computed.json')
    if '--check' in sys.argv:
        old = json.load(open(cpath)) if os.path.exists(cpath) else {}
        drift = [k for k in set(old) | set(computed)
                 if old.get(k, {}).get('sha256') != computed.get(k, {}).get('sha256')]
        if drift:
            print('DRIFT:', *drift, sep='\n  ')
            return 1
        print('ok: %d files, no drift' % len(computed))
        return 0
    json.dump(computed, open(cpath, 'w'), indent=1, sort_keys=True)

    ppath = os.path.join(HERE, '_provenance.json')
    prov = json.load(open(ppath)) if os.path.exists(ppath) else {}
    records = []
    for rel in sorted(computed):
        rec = {'path': rel}
        rec.update(prov.get(rel, {'PROVENANCE_MISSING': True}))
        rec.update(computed[rel])
        records.append(rec)
    json.dump({
        'schema': 'elder-souls/reference-manifest@1',
        'spec': 'docs/REFERENCE-IMAGE-REQUEST.md §9',
        'note': 'Numeric fields come from make-manifest.py. Provenance fields come from '
                '_provenance.json and were entered by the acquiring agent.',
        'count': len(records),
        'records': records,
    }, open(os.path.join(HERE, 'MANIFEST.json'), 'w'), indent=1)
    print('wrote MANIFEST.json (%d records)' % len(records))
    return 0


if __name__ == '__main__':
    sys.exit(main())
