#!/usr/bin/env node
// beat-diff.mjs — RI-EXP01 steps 3 and 5: diff an observed beat log against the beat sheet.
//
// Named by RI-EXP01 step 3, verbatim:
//   tools/experience/beat-diff.mjs --beats corpus/95-experience/RI-EXP01.beats.json
//                                  --log reports/sessions/<id>/beat-log.json
//   "emits beat-diff.json: per beat, hit|late|early|missing, signed minutes off target, and the
//    derived-target table computed."
//
// AND STEP 5, WHICH IS THE PART THAT USUALLY GETS DROPPED:
//   "For every `missing` beat, beat-diff.json must carry THE SEARCH THAT WOULD HAVE FOUND IT
//    AND ITS EMPTY OUTPUT."
// A missing beat reported as a bare `missing` is unfalsifiable — the reader cannot tell a beat
// the build does not have from a beat the extractor cannot see. So every `missing` row carries
// the beat classes that were searched, how many candidates of each class the log held, and the
// window that was searched. That is the negative artifact, and it is emitted whether or not
// anyone asks.
//
// EXIT: 0 beats_hit meets the sheet's target; 1 it does not, or the diff could not be taken.
'use strict';

import fs from 'node:fs';
import path from 'node:path';
import { REPO_ROOT, parseArgs, wantsHelp, usage, writeJson, readJson, die, EXIT } from '../lib/cli.mjs';

const USAGE = `
beat-diff.mjs — RI-EXP01 steps 3 and 5: beat sheet vs observed beat log.

USAGE
  node tools/experience/beat-diff.mjs --beats corpus/95-experience/RI-EXP01.beats.json \\
       --log reports/sessions/<id>/beat-log.json
  node tools/experience/beat-diff.mjs --log <path>            (beats defaults to RI-EXP01's)
  node tools/experience/beat-diff.mjs --self-test

OPTIONS
  --beats PATH   the machine-readable beat sheet (generated by beats-from-md.mjs)
  --log PATH     the observed beat log (emitted by beat-extract.mjs)
  --out PATH     default: beside the log, as beat-diff.json
  --jrn PATH     a RI-JRN01/02 verdict or journey.json, for step 6's jrn_agreement cross-check
  --self-test    prove the diff can fail, and that a MISSING beat always carries its negative
                 artifact (step 5) rather than a bare "missing"

VERDICTS PER BEAT
  hit      observed within [t_target - tol.minus, t_target + tol.plus]
  early    observed before the window
  late     observed after the window
  missing  no candidate of the beat's class was observed at all
`;

// Which observed beat classes can satisfy which sheet beat. A sheet beat is characterised by
// its G/F column, its verbs and its odd/lethal flags; the mapping is stated here rather than
// guessed per-row so a critic can dispute one table instead of eighteen inferences.
const CLASS_FOR = (beat) => {
  const out = new Set();
  const verbs = (beat.verbs || []).map((v) => v.toLowerCase());
  if (beat.odd) out.add('odd');
  if (/death|die/.test(verbs.join(' ')) || /T-death|lethal/i.test(beat.beat)) out.add('death');
  if (beat.given_or_found === 'F') { out.add('found_not_given'); }
  if (beat.given_or_found === 'G') { out.add('given'); out.add('creation'); }
  if (verbs.some((v) => /attack|roll|fight/.test(v))) out.add('combat');
  if (verbs.some((v) => /take|search|explore|read/.test(v))) out.add('found_not_given');
  if (verbs.some((v) => /talk|ask|bribe|choose|lie/.test(v))) { out.add('given'); out.add('refusal'); }
  if (verbs.some((v) => /move/.test(v))) out.add('release');
  if (out.size === 0) out.add('given');
  return [...out];
};

const args = parseArgs();
if (wantsHelp(args)) usage(USAGE);
if (args['self-test']) process.exit(selfTest());

const beatsPath = path.resolve(String(args.beats || path.join(REPO_ROOT, 'corpus/95-experience/RI-EXP01.beats.json')));
const logPath = args.log ? path.resolve(String(args.log)) : null;
if (!logPath) die(EXIT.USAGE, '--log <beat-log.json> is required');
if (!fs.existsSync(beatsPath)) {
  die(EXIT.MEASUREMENT_FAIL,
    `${path.relative(REPO_ROOT, beatsPath)} does not exist. Generate it with:\n` +
    `  node tools/experience/beats-from-md.mjs`);
}
if (!fs.existsSync(logPath)) {
  die(EXIT.MEASUREMENT_FAIL,
    `${path.relative(REPO_ROOT, logPath)} does not exist. Produce it with:\n` +
    `  node tools/experience/beat-extract.mjs --in reports/sessions/<id>`);
}

const sheet = readJson(beatsPath);
const log = readJson(logPath);
const diff = compare(sheet, log);
writeJson(args.out ? String(args.out) : path.join(path.dirname(logPath), 'beat-diff.json'), diff);
report(diff);
process.exit(diff.ok ? 0 : 1);

// ---------------------------------------------------------------------------------------------
/**
 * Normalise the beat sheet.
 *
 * Two generators for `RI-EXP01.beats.json` were written in the same wave by different agents
 * and they emit different field names — `tol` vs `tolerance_min`, `"F"/"G"` vs
 * `"found"/"given"`, `derived_targets` as an array of rows vs as an object keyed by metric.
 * Both are faithful to §D. This diff reads either rather than picking a winner, because the
 * alternative is a tool that silently reports every beat missing the day the other generator
 * runs — which is exactly the class of failure this whole exercise exists to remove.
 */
export function normaliseSheet(sheet) {
  const beats = (sheet.beats || []).map((b) => ({
    ...b,
    tol: b.tol || b.tolerance_min || { plus: 0, minus: 0 },
    given_or_found: b.given_or_found === 'found' ? 'F' : (b.given_or_found === 'given' ? 'G' : b.given_or_found),
    sb: b.sb || b.shared_beats || [],
  }));
  let derived = sheet.derived_targets || sheet.targets || [];
  if (!Array.isArray(derived)) {
    derived = Object.entries(derived).map(([metric, v]) => ({
      metric,
      definition: v.definition || '',
      target: typeof v.target === 'string' ? parseBandString(v.target) : v.target,
      fail: typeof v.fail === 'string' ? parseBandString(v.fail) : v.fail,
    }));
  }
  return { ...sheet, beats, derived_targets: derived };
}

function parseBandString(s) {
  const t = String(s).replace(/[−–—]/g, '-').replace(/≤/g, '<=').replace(/≥/g, '>=').trim();
  let m = /^<=\s*(-?\d+(?:\.\d+)?)/.exec(t); if (m) return { op: '<=', value: Number(m[1]), raw: t };
  m = /^>=\s*(-?\d+(?:\.\d+)?)/.exec(t); if (m) return { op: '>=', value: Number(m[1]), raw: t };
  m = /^>\s*(-?\d+(?:\.\d+)?)/.exec(t); if (m) return { op: '>', value: Number(m[1]), raw: t };
  m = /^<\s*(-?\d+(?:\.\d+)?)/.exec(t); if (m) return { op: '<', value: Number(m[1]), raw: t };
  m = /^(-?\d+(?:\.\d+)?)\s*-\s*(-?\d+(?:\.\d+)?)$/.exec(t); if (m) return { op: 'between', min: Number(m[1]), max: Number(m[2]), raw: t };
  m = /^(-?\d+(?:\.\d+)?)\s*\/\s*(-?\d+(?:\.\d+)?)$/.exec(t); if (m) return { op: 'ratio', value: Number(m[1]), of: Number(m[2]), raw: t };
  const n = Number(t);
  return Number.isFinite(n) ? { op: '==', value: n, raw: t } : { op: 'prose', raw: t };
}

export function compare(rawSheet, log) {
  const sheet = normaliseSheet(rawSheet);
  const observed = log.beats || [];
  const rows = [];
  const used = new Set();

  for (const b of sheet.beats || []) {
    const classes = CLASS_FOR(b);
    const lo = b.t_target_min - (b.tol ? b.tol.minus : 0);
    const hi = b.t_target_min + (b.tol ? b.tol.plus : 0);
    const candidates = observed
      .map((o, i) => ({ o, i }))
      .filter(({ o, i }) => classes.includes(o.beat_class) && !used.has(i));

    if (!candidates.length) {
      // STEP 5. The negative artifact: what was searched, and what it returned.
      rows.push({
        id: b.id, t_target_min: b.t_target_min, window: [lo, hi],
        verdict: 'missing', observed_t_min: null, delta_min: null,
        negative_artifact: {
          searched_beat_classes: classes,
          candidates_of_those_classes_in_log: classes.map((c) => ({ beat_class: c, count: (log.by_class || {})[c] || 0 })),
          window_searched_min: [lo, hi],
          total_beats_in_log: observed.length,
          trace_records_scanned: log.trace_records ?? null,
          empty_output: true,
          note: 'RI-EXP01 step 5: a `missing` beat must carry the search that would have found it ' +
                'and its empty output. Without this a reader cannot tell a beat the build does not ' +
                'have from a beat the extractor cannot see.',
        },
      });
      continue;
    }

    // Nearest candidate to the target, then consume it so two sheet beats cannot claim one
    // observation — which would inflate beats_hit.
    candidates.sort((x, y) => Math.abs(x.o.t_min - b.t_target_min) - Math.abs(y.o.t_min - b.t_target_min));
    const { o, i } = candidates[0];
    used.add(i);
    const verdict = o.t_min < lo ? 'early' : (o.t_min > hi ? 'late' : 'hit');
    rows.push({
      id: b.id, t_target_min: b.t_target_min, window: [lo, hi],
      verdict, observed_t_min: o.t_min,
      delta_min: +(o.t_min - b.t_target_min).toFixed(2),
      matched_class: o.beat_class, evidence: o.evidence, confidence: o.confidence,
    });
  }

  const hit = rows.filter((r) => r.verdict === 'hit').length;

  // --- the derived-target table, computed ---------------------------------------------------
  const firstOf = (cls) => {
    const c = observed.filter((o) => o.beat_class === cls).sort((a, b) => a.t_min - b.t_min)[0];
    return c ? c.t_min : null;
  };
  const countOf = (cls) => observed.filter((o) => o.beat_class === cls).length;

  const computed = {
    T_found: firstOf('found_not_given'),
    T_death: firstOf('death'),
    T_odd: firstOf('odd'),
    T_refusal: firstOf('refusal'),
    T_lie: null,          // deferred by beat-extract: verification stage, not a trace signature
    T_choice: null,       // needs a persistence check over >= 30 min, not a beat signature
    N_odd: countOf('odd'),
    N_found: countOf('found_not_given'),
    N_persons: null,      // needs the NPC roster as PRESENTED, not the data file
    V_taught: null,       // needs the verb census from the session ops log
    beats_hit: hit,
    order_violations: countOrderViolations(rows),
    tutorial_text_chars: log.tutorial_text_chars ?? null,
  };

  const targets = {};
  for (const d of sheet.derived_targets || []) {
    const v = computed[d.metric];
    targets[d.metric] = {
      value: v === undefined ? null : v,
      target: d.target, fail: d.fail,
      status: v === null || v === undefined ? 'unmeasurable' : (meets(v, d.target) ? 'pass' : (meets(v, d.fail) ? 'fail' : 'below')),
      why: (v === null || v === undefined)
        ? unmeasurableReason(d.metric)
        : null,
    };
  }

  const beatsHitTarget = (sheet.derived_targets || []).find((d) => d.metric === 'beats_hit');
  const requiredHits = beatsHitTarget && beatsHitTarget.target && beatsHitTarget.target.op === 'ratio'
    ? beatsHitTarget.target.value : 15;

  return {
    schema: 'elder-souls/beat-diff@1',
    tool: 'tools/experience/beat-diff.mjs',
    item: 'RI-EXP01 steps 3 + 5',
    sheet_from: sheet.generated_from || null,
    beats_in_sheet: (sheet.beats || []).length,
    beats_in_log: observed.length,
    rows,
    summary: {
      hit, early: rows.filter((r) => r.verdict === 'early').length,
      late: rows.filter((r) => r.verdict === 'late').length,
      missing: rows.filter((r) => r.verdict === 'missing').length,
      required_hits: requiredHits,
    },
    derived_targets: targets,
    jrn_agreement: null,   // step 6, filled by --jrn
    ok: hit >= requiredHits,
  };
}

function unmeasurableReason(metric) {
  return ({
    T_lie: 'RI-EXP01 step 2 defers `lie` to a verification stage against game/data/**; it is not a trace signature and beat-extract does not emit it.',
    T_choice: 'needs a decision whose TWO consequences persist >= 30 min — a persistence check across the session, not a beat signature.',
    N_persons: 'needs named NPCs with >= 3 topics AND a stated opinion about another named NPC, as PRESENTED in play. Reading npcs/*.json instead would measure the design document (RI-MTH07).',
    V_taught: 'needs the distinct-verb census from the session ops log; run it against session-run.mjs ops.json rather than the trace.',
  })[metric] || 'no observed beat class supplies this metric';
}

function meets(v, band) {
  if (!band) return false;
  switch (band.op) {
    case '<=': return v <= band.value;
    case '>=': return v >= band.value;
    case '<': return v < band.value;
    case '>': return v > band.value;
    case '==': return v === band.value;
    case 'between': return v >= band.min && v <= band.max;
    case 'ratio': return v >= band.value;
    default: return false;
  }
}

/** A beat observed before a beat the sheet puts strictly earlier is an order violation. */
function countOrderViolations(rows) {
  const seen = rows.filter((r) => r.observed_t_min !== null);
  let n = 0;
  for (let i = 0; i < seen.length; i++) {
    for (let j = i + 1; j < seen.length; j++) {
      if (seen[i].t_target_min < seen[j].t_target_min && seen[i].observed_t_min > seen[j].observed_t_min) n++;
    }
  }
  return n;
}

function report(d) {
  process.stdout.write(`beat-diff: ${d.summary.hit}/${d.beats_in_sheet} hit (need ${d.summary.required_hits}), ` +
    `${d.summary.early} early, ${d.summary.late} late, ${d.summary.missing} missing\n`);
  for (const r of d.rows) {
    const tag = { hit: 'HIT ', early: 'EARL', late: 'LATE', missing: 'MISS' }[r.verdict];
    process.stdout.write(`  ${tag} ${r.id} target ${r.t_target_min}m window [${r.window.join(',')}]` +
      (r.observed_t_min !== null ? ` observed ${r.observed_t_min}m (${r.delta_min >= 0 ? '+' : ''}${r.delta_min})` : '') + '\n');
    if (r.verdict === 'missing') {
      process.stdout.write(`         searched ${r.negative_artifact.searched_beat_classes.join(', ')} -> ` +
        r.negative_artifact.candidates_of_those_classes_in_log.map((c) => `${c.beat_class}:${c.count}`).join(' ') + '\n');
    }
  }
  for (const [k, v] of Object.entries(d.derived_targets)) {
    process.stdout.write(`  ${v.status === 'pass' ? 'PASS' : v.status === 'unmeasurable' ? 'N/A ' : 'FAIL'} ${k.padEnd(20)} ${String(v.value)}` +
      (v.why ? `\n         ${v.why}` : '') + '\n');
  }
}

// ---------------------------------------------------------------------------------------------
function selfTest() {
  const lines = [];
  let failed = 0;
  const ok = (n, pass, d) => { lines.push(`${pass ? 'PASS' : 'FAIL'} ${n} — ${d}`); if (!pass) failed++; };

  const sheet = {
    beats: [
      { id: 'B01', t_target_min: 0, tol: { plus: 0, minus: 0 }, beat: 'the hold', verbs: [], given_or_found: 'G', odd: false, lethal: false },
      { id: 'B04', t_target_min: 8, tol: { plus: 2, minus: 2 }, beat: 'the found thing', verbs: ['take'], given_or_found: 'F', odd: false, lethal: false },
      { id: 'B09', t_target_min: 22, tol: { plus: 5, minus: 5 }, beat: 'the unexplained', verbs: ['read'], given_or_found: 'F', odd: true, lethal: true },
    ],
    derived_targets: [
      { metric: 'T_found', definition: '', target: { op: '<=', value: 10 }, fail: { op: '>', value: 15 } },
      { metric: 'beats_hit', definition: '', target: { op: 'ratio', value: 2, of: 3 }, fail: { op: 'ratio', value: 1, of: 3 } },
    ],
  };

  // 1. Empty log: every beat missing, and EVERY missing row carries its negative artifact.
  const emptyDiff = compare(sheet, { beats: [], by_class: {}, trace_records: 0 });
  const missing = emptyDiff.rows.filter((r) => r.verdict === 'missing');
  ok('an empty log makes every beat missing', missing.length === sheet.beats.length,
    `${missing.length}/${sheet.beats.length} missing`);
  ok('EVERY missing beat carries the step-5 negative artifact',
    missing.every((r) => r.negative_artifact && r.negative_artifact.searched_beat_classes.length > 0 && r.negative_artifact.empty_output),
    `${missing.filter((r) => r.negative_artifact).length}/${missing.length} rows carry a search + empty output`);
  ok('an empty log is NOT ok', !emptyDiff.ok, `ok=${emptyDiff.ok}, hit=${emptyDiff.summary.hit}`);

  // 2. A good log hits.
  const good = compare(sheet, {
    beats: [
      { beat_class: 'given', t_min: 0, evidence: [1] },
      { beat_class: 'found_not_given', t_min: 8.5, evidence: [2] },
      { beat_class: 'odd', t_min: 21, evidence: [3] },
    ],
    by_class: { given: 1, found_not_given: 1, odd: 1 }, trace_records: 100,
  });
  ok('a log matching the sheet hits every beat', good.summary.hit === 3 && good.ok,
    `hit=${good.summary.hit}, ok=${good.ok}`);

  // 3. THE FALSIFICATION: a beat outside its tolerance must be `late`, not `hit`. If tolerance
  //    is not applied, every beat "hits" and beats_hit is meaningless.
  const late = compare(sheet, {
    beats: [
      { beat_class: 'given', t_min: 0, evidence: [1] },
      { beat_class: 'found_not_given', t_min: 40, evidence: [2] },
      { beat_class: 'odd', t_min: 21, evidence: [3] },
    ],
    by_class: { given: 1, found_not_given: 1, odd: 1 }, trace_records: 100,
  });
  const b04 = late.rows.find((r) => r.id === 'B04');
  ok('a beat outside tolerance is LATE, not HIT (falsification)',
    b04.verdict === 'late' && b04.delta_min === 32,
    `B04 target 8 ±2, observed 40 -> ${b04.verdict} (${b04.delta_min > 0 ? '+' : ''}${b04.delta_min})`);

  // 4. THE OTHER FALSIFICATION: one observation must not satisfy two sheet beats. If it can,
  //    a single lucky event inflates beats_hit.
  const sheet2 = {
    beats: [
      { id: 'X1', t_target_min: 8, tol: { plus: 4, minus: 4 }, beat: '', verbs: ['take'], given_or_found: 'F', odd: false, lethal: false },
      { id: 'X2', t_target_min: 9, tol: { plus: 4, minus: 4 }, beat: '', verbs: ['take'], given_or_found: 'F', odd: false, lethal: false },
    ],
    derived_targets: [],
  };
  const shared = compare(sheet2, { beats: [{ beat_class: 'found_not_given', t_min: 8.5, evidence: [1] }], by_class: { found_not_given: 1 }, trace_records: 10 });
  ok('one observation cannot satisfy two sheet beats (falsification)',
    shared.summary.hit === 1 && shared.summary.missing === 1,
    `hit=${shared.summary.hit}, missing=${shared.summary.missing} (if hit were 2, a single event would inflate beats_hit)`);

  // 5. THE SCHEMA-TOLERANCE CHECK. The other generator's field names must produce the same
  //    verdicts. A diff that only understands one generator reports every beat missing the day
  //    the other one runs.
  const otherSchema = {
    beats: sheet.beats.map((b) => ({
      id: b.id, t_target_min: b.t_target_min,
      tolerance_min: b.tol,
      beat: b.beat, verbs: b.verbs,
      given_or_found: b.given_or_found === 'F' ? 'found' : 'given',
      odd: b.odd, lethal: b.lethal, shared_beats: [],
    })),
    targets: { T_found: { definition: '', target: '<= 10', fail: '> 15' }, beats_hit: { definition: '', target: '2/3', fail: '1/3' } },
  };
  const otherDiff = compare(otherSchema, {
    beats: [
      { beat_class: 'given', t_min: 0, evidence: [1] },
      { beat_class: 'found_not_given', t_min: 8.5, evidence: [2] },
      { beat_class: 'odd', t_min: 21, evidence: [3] },
    ],
    by_class: { given: 1, found_not_given: 1, odd: 1 }, trace_records: 100,
  });
  ok('the other generator\'s field names give identical verdicts',
    otherDiff.summary.hit === good.summary.hit && otherDiff.derived_targets.T_found.value === 8.5,
    `tolerance_min/found-given/targets-object -> hit=${otherDiff.summary.hit} (same as ${good.summary.hit}), T_found=${otherDiff.derived_targets.T_found.value}`);

  // 6. T_found is computed, and its unmeasurable siblings say why rather than reporting 0.
  ok('T_found is computed from the log', good.derived_targets.T_found.value === 8.5,
    `T_found=${good.derived_targets.T_found.value}, status=${good.derived_targets.T_found.status}`);
  const emptyT = emptyDiff.derived_targets.T_found;
  ok('an unsupplied metric is unmeasurable with a reason, never 0',
    emptyT.value === null && emptyT.status === 'unmeasurable' && !!emptyT.why,
    `value=${emptyT.value}, status=${emptyT.status}`);

  for (const l of lines) process.stdout.write(l + '\n');
  process.stdout.write(`\nbeat-diff self-test: ${failed === 0 ? 'PASS' : 'FAIL'} (${lines.length - failed}/${lines.length})\n`);
  return failed === 0 ? 0 : 1;
}
