#!/usr/bin/env node
// RI-EXP06 result validator. Producers write four observed arms per frozen probe; this gate refuses
// static substrate scans, missing arms, target self-reports, or a restore that did not reopen.
import fs from 'node:fs'; import crypto from 'node:crypto';
const a=process.argv.slice(2),v=k=>{const i=a.indexOf(`--${k}`);return i<0?null:a[i+1]},probes=v('probes')||'corpus/95-experience/RI-EXP06.probes.json',results=v('results'),out=v('out');
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const sha=x=>typeof x==='string'&&/^[0-9a-f]{64}$/.test(x);
export function validate(register, rows){const by=new Map(rows.map(x=>[x.id,x])),live=(register.probes||register.entries||[]).filter(x=>x.live!==false&&x.status!=='struck'),checks=live.map(p=>{const r=by.get(p.id),arms=r?.arms||{};const complete=['baseline','closure','repeat','restore'].every(k=>arms[k]?.observed===true);const provenance=complete&&typeof r.browser_session_id==='string'&&r.browser_session_id.length>0&&Number.isInteger(r.frame_start)&&Number.isInteger(r.frame_end)&&r.frame_end>r.frame_start&&['baseline','closure','repeat','restore'].every(k=>sha(arms[k].source_sha256)&&sha(arms[k].target_sha256));const open=complete&&arms.baseline.usable===true&&arms.restore.usable===true,closed=complete&&arms.repeat.usable===false&&arms.repeat.player_facing===true;const distinct=complete&&digest(arms.baseline.target)!==digest(arms.repeat.target),restored=complete&&digest(arms.baseline.target)===digest(arms.restore.target)&&arms.baseline.source_sha256===arms.restore.source_sha256,repeated=complete&&digest(arms.closure.target)===digest(arms.repeat.target);const executed=complete&&arms.closure.executed===true&&arms.closure.changed_hash===true&&sha(arms.closure.source_sha256)&&sha(arms.restore.source_sha256)&&arms.closure.source_sha256!==arms.restore.source_sha256;const realConsumer=complete&&r.consumer_execution?.count>0&&typeof r.consumer_execution?.consumer==='string'&&Array.isArray(r.consumer_execution?.frames)&&r.consumer_execution.frames.length>0&&r.consumer_execution.frames.every(Number.isInteger),noDirect=complete&&r.direct_target_mutation===false;return{id:p.id,complete,live_provenance:provenance,baseline_open:open,closure_repeated:repeated,executed,player_facing_refusal:distinct&&closed,real_consumer_execution:realConsumer,restored,no_direct_target_mutation:noDirect,pass:complete&&provenance&&open&&closed&&distinct&&repeated&&executed&&realConsumer&&restored&&noDirect};});const ids=new Set(live.map(x=>x.id)),extras=rows.filter(x=>!ids.has(x.id)).map(x=>x.id);return{checks,declared:live.length,passed:checks.filter(x=>x.pass).length,probes_run_fraction:checks.filter(x=>x.complete&&x.live_provenance).length/Math.max(1,live.length),extra_rows:extras,pass:checks.length>0&&checks.every(x=>x.pass)&&extras.length===0};}
if(a.includes('--self-test')){const h=x=>crypto.createHash('sha256').update(x).digest('hex'),open=h('open'),closed=h('closed'),reg={entries:[{id:'B-01',status:'live'}]},good={id:'B-01',browser_session_id:'browser-1',frame_start:10,frame_end:20,direct_target_mutation:false,consumer_execution:{consumer:'Engine.tryAction',count:2,frames:[12,14]},arms:{baseline:{observed:true,usable:true,source_sha256:open,target_sha256:h('OPEN'),target:'OPEN'},closure:{observed:true,executed:true,changed_hash:true,source_sha256:closed,target_sha256:h('REFUSED'),target:'REFUSED'},repeat:{observed:true,usable:false,player_facing:true,source_sha256:closed,target_sha256:h('REFUSED'),target:'REFUSED'},restore:{observed:true,usable:true,source_sha256:open,target_sha256:h('OPEN'),target:'OPEN'}}};const bad=[[],[{...good,direct_target_mutation:true}],[{...good,consumer_execution:{count:0,frames:[]}}],[{...good,browser_session_id:null}],[{...good,arms:{...good.arms,restore:{...good.arms.restore,source_sha256:h('not-open')}}}],[{...good,arms:{...good.arms,repeat:{...good.arms.repeat,target:'DIFFERENT'}}}]];if(!validate(reg,[good]).pass||bad.some(x=>validate(reg,x).pass))process.exit(1);console.log('PASS permissiveness-live: live provenance + open→closure→repeat refusal→restore; missing/direct/inert/unconsumed red');process.exit()}
if(!results){console.error('usage: --results live-arms.json [--probes register] --out report.json');process.exit(2)}const reg=JSON.parse(fs.readFileSync(probes)),rows=JSON.parse(fs.readFileSync(results));const report={schema:'elder-souls/permissiveness-live@2',register_sha256:digest(reg),...validate(reg,Array.isArray(rows)?rows:rows.rows||[]),chain_status:rows.chain_status||'NOT_RUN',chain_discrepancies:rows.chain_discrepancies??null};report.pass=report.pass&&report.chain_status==='PASS'&&report.chain_discrepancies===0;if(out)fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(report.pass?'PASS':`RED ${report.passed}/${report.declared}, run_fraction=${report.probes_run_fraction}`);process.exit(report.pass?0:1);
