#!/usr/bin/env node
// RI-EXP06 result validator. Producers write four observed arms per frozen probe; this gate refuses
// static substrate scans, missing arms, target self-reports, or a restore that did not reopen.
import fs from 'node:fs'; import crypto from 'node:crypto';
const a=process.argv.slice(2),v=k=>{const i=a.indexOf(`--${k}`);return i<0?null:a[i+1]},probes=v('probes')||'corpus/95-experience/RI-EXP06.probes.json',results=v('results'),out=v('out');
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
export function validate(register, rows){const by=new Map(rows.map(x=>[x.id,x])),live=(register.probes||register.entries||[]).filter(x=>x.live!==false),checks=live.map(p=>{const r=by.get(p.id);const arms=r?.arms||{};const complete=['baseline','closure','repeat','restore'].every(k=>arms[k]&&arms[k].observed===true);const distinct=complete&&digest(arms.baseline.target)!==digest(arms.repeat.target);const restored=complete&&digest(arms.baseline.target)===digest(arms.restore.target);const executed=complete&&arms.closure.executed===true&&arms.closure.changed_hash===true;const noDirect=complete&&r.direct_target_mutation!==true;return{id:p.id,complete,executed,player_facing_refusal:distinct,restored,no_direct_target_mutation:noDirect,pass:complete&&executed&&distinct&&restored&&noDirect};});return{checks,declared:live.length,passed:checks.filter(x=>x.pass).length,probes_run_fraction:checks.filter(x=>x.complete).length/Math.max(1,live.length),pass:checks.length>0&&checks.every(x=>x.pass)};}
if(a.includes('--self-test')){const reg={probes:[{id:'B-01'}]},good={id:'B-01',arms:{baseline:{observed:true,target:'OPEN'},closure:{observed:true,executed:true,changed_hash:true,target:'mutation'},repeat:{observed:true,target:'REFUSED'},restore:{observed:true,target:'OPEN'}}};if(!validate(reg,[good]).pass||validate(reg,[]).pass||validate(reg,[{...good,direct_target_mutation:true}]).pass)process.exit(1);console.log('PASS permissiveness-live: open→closure→refused→restore; missing/direct mutation red');process.exit()}
if(!results){console.error('usage: --results live-arms.json [--probes register] --out report.json');process.exit(2)}const reg=JSON.parse(fs.readFileSync(probes)),rows=JSON.parse(fs.readFileSync(results));const report={schema:'elder-souls/permissiveness-live@1',register_sha256:digest(reg),...validate(reg,Array.isArray(rows)?rows:rows.rows||[]),chain_status:'NOT_RUN'};if(out)fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(report.pass?'PASS':`RED ${report.passed}/${report.declared}, run_fraction=${report.probes_run_fraction}`);process.exit(report.pass?0:1);
