#!/usr/bin/env node
// RI-EXP06 result validator. Producers write four observed arms per frozen probe; this gate refuses
// static substrate scans, missing arms, target self-reports, or a restore that did not reopen.
import fs from 'node:fs'; import crypto from 'node:crypto';
const a=process.argv.slice(2),v=k=>{const i=a.indexOf(`--${k}`);return i<0?null:a[i+1]},probes=v('probes')||'corpus/95-experience/RI-EXP06.probes.json',results=v('results'),out=v('out');
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
export function validate(register, rows){const by=new Map(rows.map(x=>[x.id,x])),live=(register.probes||register.entries||[]).filter(x=>x.live!==false),checks=live.map(p=>{const r=by.get(p.id),arms=r?.arms||{};const complete=['baseline','closure','repeat','restore'].every(k=>arms[k]?.observed===true);const open=complete&&arms.baseline.usable===true&&arms.restore.usable===true,closed=complete&&arms.repeat.usable===false&&arms.repeat.player_facing===true;const distinct=complete&&digest(arms.baseline.target)!==digest(arms.repeat.target),restored=complete&&digest(arms.baseline.target)===digest(arms.restore.target),repeated=complete&&digest(arms.closure.target)===digest(arms.repeat.target);const executed=complete&&arms.closure.executed===true&&arms.closure.changed_hash===true&&typeof arms.closure.source_sha256==='string'&&typeof arms.restore.source_sha256==='string'&&arms.closure.source_sha256!==arms.restore.source_sha256;const realConsumer=complete&&r.consumer_execution?.count>0&&typeof r.consumer_execution?.consumer==='string',noDirect=complete&&r.direct_target_mutation!==true;return{id:p.id,complete,baseline_open:open,closure_repeated:repeated,executed,player_facing_refusal:distinct&&closed,real_consumer_execution:realConsumer,restored,no_direct_target_mutation:noDirect,pass:complete&&open&&closed&&distinct&&repeated&&executed&&realConsumer&&restored&&noDirect};});const ids=new Set(live.map(x=>x.id)),extras=rows.filter(x=>!ids.has(x.id)).map(x=>x.id);return{checks,declared:live.length,passed:checks.filter(x=>x.pass).length,probes_run_fraction:checks.filter(x=>x.complete).length/Math.max(1,live.length),extra_rows:extras,pass:checks.length>0&&checks.every(x=>x.pass)&&extras.length===0};}
if(a.includes('--self-test')){const reg={probes:[{id:'B-01'}]},good={id:'B-01',consumer_execution:{consumer:'Engine.tryAction',count:1},arms:{baseline:{observed:true,usable:true,target:'OPEN'},closure:{observed:true,executed:true,changed_hash:true,source_sha256:'closed',target:'REFUSED'},repeat:{observed:true,usable:false,player_facing:true,target:'REFUSED'},restore:{observed:true,usable:true,source_sha256:'open',target:'OPEN'}}};const bad=[[],[{...good,direct_target_mutation:true}],[{...good,consumer_execution:{count:0}}],[{...good,arms:{...good.arms,repeat:{...good.arms.repeat,target:'DIFFERENT'}}}]];if(!validate(reg,[good]).pass||bad.some(x=>validate(reg,x).pass))process.exit(1);console.log('PASS permissiveness-live: open→closure→repeat refusal→restore; missing/direct/inert/unconsumed red');process.exit()}
if(!results){console.error('usage: --results live-arms.json [--probes register] --out report.json');process.exit(2)}const reg=JSON.parse(fs.readFileSync(probes)),rows=JSON.parse(fs.readFileSync(results));const report={schema:'elder-souls/permissiveness-live@2',register_sha256:digest(reg),...validate(reg,Array.isArray(rows)?rows:rows.rows||[]),chain_status:rows.chain_status||'NOT_RUN',chain_discrepancies:rows.chain_discrepancies??null};report.pass=report.pass&&report.chain_status==='PASS'&&report.chain_discrepancies===0;if(out)fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(report.pass?'PASS':`RED ${report.passed}/${report.declared}, run_fraction=${report.probes_run_fraction}`);process.exit(report.pass?0:1);
