#!/usr/bin/env node
// Prose-voice integrity for every player-facing register, checked over the JSON with no engine
// and no browser.
//
// WHY THIS EXISTS
// ---------------
// W1-PROSE-TICS removed 768 `-body` forms from the shipped corpus. Within hours other agents'
// work landed and the count was **216 again**. The builder wrote the lesson down and the round-1
// blind judge confirmed it from the other side:
//
//   > A prose constraint fixed once and not enforced by a check that RUNS decays within hours
//   > on a busy tree.
//
// So this is the gate. It is the only thing in the piece that keeps working after the agent that
// wrote the prose has exited.
//
// WARNING, NOT AN ERROR, AND DELIBERATELY SO — the precedent is `tools/check-quests.mjs`'s
// attribute-scale audit, and the reason is the same. The dialogue and book data belong to a dozen
// other pieces. A fail-closed assertion landed here would turn a shared check red for every agent
// on the box over content none of them owns, which is a failure this project has already paid for
// twice. It prints loudly and exits 0. `--strict` exits non-zero for a pre-commit hook or for a
// piece that wants to hold its own line.
//
// WHAT IT MEASURES, AND WHY THESE
// -------------------------------
// Every bar is calibrated against the reference corpus — Morrowind's own 1.86 M words of dialogue,
// 186 k of book prose and 92 k of journal entries — not against anybody's taste. The calibration
// lives in `tools/prose/prose-bars.json`, is regenerated by `--calibrate`, and records the
// reference rate next to every bar so a reader can see what the bar is made of.
//
//   questions      Nobody in our world asks the player anything. 24.4 per 10k against 158.8.
//                  A FLOOR, per file: a dialogue file where no one is curious is the defect.
//   exclamations   Zero across 7,648 words of the newest material; 34.7 per 10k in the swept
//                  greetings against the reference's 21.3. A BAND — both ends are wrong, and the
//                  seam between them is worse for a reader than either.
//   sting          The closing punchline. 43.5 per 10k against 1.6 — a 27x separator, and the one
//                  the round-1 judge said no regex would find. A CAP.
//   fragopen       Sentence-initial `Which` fragments. Round 1 invented this construction while
//                  fixing something else and left it at 11x the reference. A CAP.
//   andopen        Sentence-initial And/But/So. Round 1 took the rewritten lines to 60.65 against
//                  the reference's 27.47 while the untouched corpus sat at 12.39. A BAND, for the
//                  same reason as exclamations: the bimodality is the tell.
//   contractions   Same shape. `greetings.json` 463.7 against 327.8; `50-factions.json` 25.1.
//                  A BAND.
//   tics           `-body` forms (the 2 -> 216 regression), filler `eleven` (a countable-looking
//                  number in front of an uncountable noun), and the house cadence
//                  `that is what/why/all` at 55x.
//
// THE RATCHET
// -----------
// A bar set to the reference rate is red on every file in the corpus on the day it lands, and a
// check that is red everywhere is a check nobody reads. So each metric carries TWO numbers:
//
//   * `target` — the reference rate. Never moves. Always printed as the distance still to go.
//   * `ceiling`/`floor` — the ratchet, recorded from the corpus as it stood when the bar was last
//     baselined. A file that is WORSE than the ratchet is a regression and warns loudly. A file
//     that is better than the ratchet but short of the target is reported quietly under `--verbose`.
//
// Re-baseline with `--calibrate` only after a pass that genuinely improved the corpus; that locks
// the improvement in and makes the next regression visible. A `--calibrate` run that would LOOSEN
// a ratchet refuses and says so, because a ratchet you can quietly reset is not a ratchet.
//
// USAGE
//   node tools/check-prose.mjs                  # the gate: loud warnings, exit 0
//   node tools/check-prose.mjs --verbose        # every file and every metric
//   node tools/check-prose.mjs --strict         # exit 1 on any regression past the ratchet
//   node tools/check-prose.mjs --calibrate      # regenerate tools/prose/prose-bars.json
//   node tools/check-prose.mjs --self-test      # prove it goes red, and prove it stays quiet
//   node tools/check-prose.mjs --file <path>    # one file's numbers, with examples
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BARS_FILE = path.join(ROOT, 'tools/prose/prose-bars.json');

// ------------------------------------------------------------------ text primitives
// Kept local rather than imported from tic-detector.mjs so the gate has no dependency on the
// reference corpus, the xz extract or the 69k-row CSV. `--calibrate` needs those; the check does
// not, and a gate that cannot run without a 1.8 M-word decompress is a gate that gets skipped.
export function words(s) { return (String(s).trim().match(/[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu) || []).length; }

export function sentences(s) {
  return String(s)
    .replace(/\s+/g, ' ')
    .split(/(?<=[.!?])["'”’)\]]*\s+(?=[A-Z"'“(\[])/)
    .map((x) => x.trim())
    .filter(Boolean);
}

const STOP = new Set(('a an the and or but so of to in on at by for with from as is are was were be been being it its this that these those they them their there here he she his her him you your i me my we our us not no do does did done have has had will would can could should shall may might must if then than when where which who whom what how why all any some more most much many other another same such own too very just also now still yet again once each every both few one two'
).split(/\s+/));

// ------------------------------------------------------------------ the metrics
// Each returns a raw COUNT for a single passage. Rates are counts per 10,000 words, computed by
// the caller over a whole file so that one short line cannot swing a file's figure.

export function countQuestions(t) { return (t.match(/\?/g) || []).length; }
export function countExclamations(t) { return (t.match(/!/g) || []).length; }

// THE CLOSING STING. The round-1 judge's §3.2: "Every line lands. Nothing is allowed to be flat."
//
// Two shapes, and the choice of which two is the whole of the measurement:
//
//   (b) a short closing sentence that is a fragment recasting what came before —
//       "Which is deliberate."  "That is the whole of it."  "Nobody counted twice."
//   (c) a trailing subordinate clause promoted to a verdict —
//       "…, which is how everyone else came to know it."   "…, and that is the point."
//
// DELIBERATELY NOT COUNTED: the epigram-echo, a short closing sentence repeating a content word
// from an earlier one — "That is not a mistake. A mistake happens once." It reads like our tic and
// it is not. Measured against the reference it comes in at 1.16x in dialogue and 0.79x in books:
// Morrowind writes epigrams at the same rate we do and slightly more of them in its books. Gating
// on it would have driven a rewrite that made the prose worse and moved nothing. The separator is
// not wit; it is the habit of appending an interpretation to a fact.
// NOTE THE CONTRACTED FORMS. The first version of these matched `That is` and not `That's`, so
// running a contraction sweep over the corpus would have HIDDEN stings from the sting cap while
// changing nothing a reader sees — the exact "same fingerprint in a hat" move round 1 spent its
// whole run arguing against, arriving this time through the instrument instead of the prose.
export const STING_OPENERS = /^(which|that(['’]s| is| was)|and that|but that|nor that|not that|only that|all of it|nobody|no one|none of)\b/i;
export const STING_TRAILING = /,\s*(which|and that|but that)(['’]s|\b)/i;
export const STING_RECAST = /\bwhich is (how|why|what|the|exactly|not)\b/i;

export function stingKinds(text) {
  const s = sentences(text);
  if (!s.length) return [];
  const L = s[s.length - 1].trim();
  const out = [];
  if (STING_TRAILING.test(L)) out.push('trailing-clause');
  if (STING_RECAST.test(L)) out.push('recast');
  // `!L.endsWith('?')` for the same reason `countFragOpen` has it: "Which is it?" and "That's a
  // fair question — is it?" are a speaker turning the conversation back on the player, which is
  // the opposite of a closing sting and the thing this round is trying to add. Charging a line for
  // it would aim the next writer at exactly the wrong target.
  if (s.length >= 2 && words(L) <= 14 && !L.endsWith('?') && STING_OPENERS.test(L)) out.push('fragment-close');
  return out;
}
export function countSting(t) { return stingKinds(t).length ? 1 : 0; }

// The epigram-echo, measured and REPORTED but never gated — see above. Kept in the tool so the
// next reader can re-check the falsification instead of taking it on trust.
//
// THE COMPOSITE NUMBER WAS HIDING THREE DIFFERENT FINDINGS AND ONE OF THEM POINTED THE WRONG WAY.
// Reported as a single rate this sat at 1.04x the reference and looked like a settled non-issue.
// Split by what the closing sentence actually DOES, measured over the whole of both corpora
// (ours 67,677 w of dialogue against the reference's 1,855,862 w):
//
//     statement   ours 21.87 /10k   reference 18.67   1.17x   <- the epigram proper. At parity.
//     question    ours  1.33 /10k   reference  4.72   0.28x   <- we do this a QUARTER as often
//     direction   ours  3.25 /10k   reference  1.08   3.00x   <- and this three times too often
//
// So "at parity" is true of the epigram proper and false of the composite. A closing sentence that
// reuses a word and ends in a question mark — "…who can count and can't be leaned on. Can you
// count?" — is a speaker recruiting the player, not a writer landing a joke, and Morrowind does it
// FOUR TIMES more than we do. Rolling it into one number with the epigram would have told the next
// writer to stop doing the thing this round exists to add. The closing direction is the opposite:
// a real mild tell, and one this round's own flattening made worse before this split showed it
// (50-mainline.json reached 9.49 /10k, nearly 9x, from ending too many lines on "Ask at X").
//
// All three stay UNGATED. The split is here so the number a reader acts on says which way to move.
const EPI_IMPERATIVE = /^(ask|go|come|take|tell|look|see|find|bring|keep|leave|walk|read|open|close|buy|sell|pay|count|watch|wait|stay|stop|start|carry|hold|move|send|say|speak|try|use|give|get|put|make|do|don['’]?t|do not|never|let|remember|forget|mind|be|listen|follow|meet|check|write)\b/i;

// Returns '' when the line does not close on an echo at all, else which KIND of close it is.
export function epigramKind(text) {
  const s = sentences(text);
  if (s.length < 2) return '';
  const L = s[s.length - 1].trim();
  if (words(L) > 8) return '';
  const head = s.slice(0, -1).join(' ').toLowerCase();
  const hs = new Set((head.match(/[a-z'’]{3,}/g) || []).filter((w) => !STOP.has(w)));
  let echo = false;
  for (const w of (L.toLowerCase().match(/[a-z'’]{3,}/g) || [])) if (!STOP.has(w) && hs.has(w)) { echo = true; break; }
  if (!echo) return '';
  if (L.endsWith('?')) return 'echo_question';
  if (EPI_IMPERATIVE.test(L)) return 'echo_direction';
  return 'echo_statement';
}

export function countEpigramEcho(text) { return epigramKind(text) ? 1 : 0; }

// Sentence-initial `Which` used as a fragment. Round 1 promoted `…, which is X` to `. Which is X.`
// on nearly every line it touched and manufactured a construction we now use at 11x the reference.
// AN INTERROGATIVE `Which` IS NOT THE TIC AND MUST NOT BE COUNTED AS ONE.
// The first version counted every sentence-initial `Which`, which put "Which is it?", "Which one,
// citizen?" and "Which tide were you drawn on?" in the same bucket as "Which is deliberate." Those
// are the opposite thing: they are a character asking the player something, the single defect this
// whole round exists to fix. A gate that charged a file for asking questions would have pushed the
// next writer away from the fix — so the interrogative is excluded, by the question mark.
export function countFragOpen(text) {
  let n = 0;
  for (const s of sentences(text)) {
    const t = s.trim();
    if (/^which\b/i.test(t) && !t.endsWith('?')) n++;
  }
  return n;
}

// Sentence-initial And/But/So. A BAND, not a cap: round 1 raised this on purpose and was right to
// (it is contraction-blind, so a find-and-replace cannot move it), and then overshot to 60.65 in
// the lines it touched against the reference's 27.47 while the rest of the corpus sat at 12.39.
export function countAndOpen(text) {
  let n = 0;
  for (const s of sentences(text)) if (/^(and|but|so)\b/i.test(s.trim())) n++;
  return n;
}

// THE POSSESSIVE CONFOUND. The obvious pattern — word + apostrophe + s/t/re/ve/ll/d/m — counts
// "Oleen's yard" and "the Ledger's book" as contractions. Measured, that inflates our dialogue from
// 208.0 to 244.9 per 10k and the reference from 292.3 to 328.5: about 15% on BOTH sides, so it
// never changed a ratio or a conclusion. It is corrected anyway, because a metric should measure
// what its name says — and because the two sides are not guaranteed to stay symmetric in a corpus
// whose proper nouns are still being written.
export const CONTRACTION = /\b(\w+n['’]t|\w+['’](re|ve|ll|d|m)|(it|that|there|here|he|she|what|who|this|let|one|how|where|when|why|somebody|someone|nothing|everything)['’]s)\b/gi;
export function countContractions(t) { return (t.match(CONTRACTION) || []).length; }

// ---- the tic list ----
// `-body` forms: the 2 -> 216 regression. NOT swapped for `-one` — the round-1 builder measured a
// `-body` -> `-one` swap and found it leaves a 5.5x pooled rule standing; the fix is a concrete
// actor, not a synonym.
export const TIC_BODY = /\b(any|some|no|every)body\b/gi;

// Filler `eleven`: the machine's favourite number standing in for "several".
//
// THE FIRST VERSION OF THIS PATTERN INCLUDED `eleven years` AND IT WAS WRONG. The round-1 verdict
// listed six residual elevens as uncountable filler, two of which were `eleven years ago` (Sedda
// Vell struck off the roll) and `eleven years of leases` (her day-books). Grepping the tree before
// rewriting them: that date is cross-referenced **eight times** in
// `game/data/quests/faction-imperial-assize.json` alone — the signed-out volume, the audit span,
// the office that never asked for the books back — plus `faction-xul-aneekh.json`'s fourth hollow
// and `magic-utility.json`'s kiln. It is a plot date a player can check, not filler, and rewriting
// it would have broken five files to satisfy a tic list.
//
// The round-1 builder had already ruled on the general case and the ruling holds: the eleven motif
// in the main quest is a DESIGN decision for the owner, touching quests, states and a sealed
// answer, not a prose defect. So this gate stays out of it and matches only `eleven` in front of a
// noun of DEGREE — a thing there is no way to count and therefore no way to have meant. That
// leaves `asked her eleven times` and `eleven chairs of wear on the floor` red, which is exactly
// the set that is genuinely indefensible.
export const TIC_ELEVEN_FILLER = /\beleven\s+(times?|chairs? of|kinds? of|sorts? of|ways? of|degrees? of|manner)\b/gi;

// The house cadence: 24.83 per 10k against the reference's 0.45. It is also what collided with a
// sealed answer by chance during round 1 and turned the leak scanner red — the scanner caught our
// tic, not a leak.
export const TIC_THAT_IS = /\bthat is (what|why|all|how|the whole)\b/gi;

const TICS = [
  ['-body form', TIC_BODY],
  ['filler eleven', TIC_ELEVEN_FILLER],
  ['"that is what/why/all"', TIC_THAT_IS],
];

export function countTics(text) {
  const out = {};
  for (const [name, re] of TICS) {
    const m = text.match(re);
    if (m) out[name] = m.length;
  }
  return out;
}

// ------------------------------------------------------------------ corpus loading
// Only ours. The reference is loaded by `--calibrate` alone, from tic-detector.mjs.
function readJSON(p) { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; } }

function walk(dir, out = []) {
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (e.name.endsWith('.json')) out.push(p);
  }
  return out;
}

// Mirrors tic-detector.mjs's ourCorpus() shapes. Kept as its own reader so this gate does not
// break when that research tool is refactored, and so a new dialogue shape shows up as a file
// with zero lines rather than as a silently-passing file.
export function ourText(root = ROOT) {
  const reg = { dialogue: [], books: [], journal: [] };
  const rel = (f) => path.relative(root, f);

  for (const f of walk(path.join(root, 'game/data/dialogue'))) {
    const d = readJSON(f); if (!d) continue;
    const push = (id, t) => { if (typeof t === 'string' && t.trim()) reg.dialogue.push({ id, file: rel(f), text: t }); };
    for (const t of d.topics || []) for (const [i, inf] of (t.infos || []).entries()) push(`${t.id}#${i}`, inf.x);
    for (const [i, g] of (d.greetings || []).entries()) push(g.id || `greet${i}`, g.x);
    for (const [i, p] of (d.pools || []).entries()) for (const [j, l] of (p.lines || []).entries()) push(`pool${i}#${j}`, l);
    for (const [i, l] of (d.lines || []).entries()) push(l.id || `line${i}`, l.x || l.text);
    for (const [i, l] of (d.race_gated || []).entries()) push(l.id || `rg${i}`, l.x);
    for (const [i, n] of (d.nodes || []).entries()) push(n.id || `node${i}`, n.line);
    for (const [town, arr] of Object.entries(d.rumours || {})) if (Array.isArray(arr)) arr.forEach((r, i) => push(`rumour:${town}#${i}`, typeof r === 'string' ? r : r?.x));
    for (const [i, q] of (d.questions || []).entries()) { push(`q${i}`, q.text); for (const [j, a] of (q.answers || []).entries()) push(`q${i}a${j}`, a.text); }
    for (const [i, l] of (d.slavery_lines_sample?.lines || []).entries()) push(`slave${i}`, l.text);
    // W1-05. `dialogue/road-directions.json` holds spoken directions in a shape this reader did
    // not know — `routes[].answers[].x` — so its 46 lines were not "a file with zero lines", they
    // were not a file at all: `--file game/data/dialogue/road-directions.json` printed the whole
    // corpus and nothing about the file. That is the silent pass the comment above warns about,
    // arriving through the collector rather than the scorer. Only `x` is spoken; `answers[].tell`
    // is authoring metadata naming what in the world contradicts a wrong answer, is never said to
    // anyone, and is deliberately left unmeasured.
    for (const r of d.routes || []) for (const [i, a] of (r.answers || []).entries()) push(`route:${r.id || 'route'}#${i}`, a.x);
  }
  for (const f of walk(path.join(root, 'game/data/npcs'))) {
    const d = readJSON(f); if (!d) continue;
    for (const n of d.npcs || []) if (n.lines?.greeting) reg.dialogue.push({ id: `npc:${n.id}`, file: rel(f), text: n.lines.greeting });
  }
  for (const f of walk(path.join(root, 'game/data/world'))) {
    const d = readJSON(f); if (!d) continue;
    for (const m of d.mysteries || []) for (const [i, r] of (m.refusals || []).entries()) if (r.x) reg.dialogue.push({ id: `refusal:${m.id}#${i}`, file: rel(f), text: r.x });
  }
  for (const f of walk(path.join(root, 'game/data/books'))) {
    const d = readJSON(f); if (!d) continue;
    const recs = Array.isArray(d.books) ? d.books : (d.id && d.text ? [d] : []);
    for (const b of recs) if (typeof b.text === 'string' && b.text.trim()) reg.books.push({ id: b.id, file: rel(f), text: b.text });
  }
  for (const f of walk(path.join(root, 'game/data/quests'))) {
    const d = readJSON(f); if (!d) continue;
    for (const q of d.quests || []) for (const [i, j] of (q.journal || []).entries()) if (j.text) reg.journal.push({ id: `${q.id}#${j.stage ?? i}`, file: rel(f), text: j.text });
  }
  return reg;
}

// ------------------------------------------------------------------ scoring
// Every rate is per 10,000 words.
export function scoreDocs(docs) {
  let w = 0;
  const c = { questions: 0, exclamations: 0, sting: 0, epigram_echo: 0, echo_statement: 0, echo_question: 0, echo_direction: 0, fragopen: 0, andopen: 0, contractions: 0 };
  const tics = {};
  for (const d of docs) {
    const t = d.text;
    w += words(t);
    c.questions += countQuestions(t);
    c.exclamations += countExclamations(t);
    c.sting += countSting(t);
    const ek = epigramKind(t);
    if (ek) { c.epigram_echo += 1; c[ek] += 1; }
    c.fragopen += countFragOpen(t);
    c.andopen += countAndOpen(t);
    c.contractions += countContractions(t);
    for (const [k, v] of Object.entries(countTics(t))) tics[k] = (tics[k] || 0) + v;
  }
  const rates = {};
  for (const [k, v] of Object.entries(c)) rates[k] = w ? (1e4 * v) / w : 0;
  return { docs: docs.length, words: w, counts: c, rates, tics };
}

export function byFile(docs) {
  const m = new Map();
  for (const d of docs) { if (!m.has(d.file)) m.set(d.file, []); m.get(d.file).push(d); }
  return new Map([...m].map(([f, ds]) => [f, scoreDocs(ds)]));
}

// ------------------------------------------------------------------ the bars
// Shape of one bar:
//   { kind: 'floor'|'cap'|'band', target: <reference rate>, floor|ceiling: <ratchet>, lo/hi: ... }
// `kind` says which direction is wrong; `target` is always the reference and never moves.
export const DEFAULT_BARS = {
  schema: 'elder-souls/prose-bars@1',
  note: 'Regenerate with `node tools/check-prose.mjs --calibrate`. `target` is the measured reference rate and must never be edited by hand; the ratchets are recorded from our corpus and may only tighten.',
  min_words: 400,   // a file smaller than this is too short for a rate to mean anything
  registers: {},
};

// A file under `min_words` is reported but never warned on: at 200 words one question mark is
// 50 per 10k and its absence is 0, and neither is a fact about the writing.

// THE UNDERSHOOT GUARD, and it is the difference between a check and a nuisance.
//
// "This file has no exclamation marks" is a fact about the writing only when the file is long
// enough that the reference rate predicts some. At the reference's 21.3 per 10k a 400-word file is
// expected to contain 0.85 of them, so zero is unremarkable and flagging it is noise. A file must
// be long enough for the reference to predict at least `MIN_EXPECTED` occurrences before the
// absence of a thing counts as evidence. Overshoot needs no such guard: one exclamation where the
// reference predicts none is still one that is there.
const MIN_EXPECTED = 2;

// ------------------------------------------------------------------ declared register exemptions
//
// WHY THIS EXISTS, AND WHY IT IS AS NARROW AS IT IS.
//
// `game/data/dialogue/topics/main-quest-argument.json` is the climax of the main quest: four
// hundred years of a clerk under the Stone Wastes, and its own `voice_note` specifies the register
// against a corpus item — "long sentences, impersonal passive, agency placed in an institution
// rather than in the speaker … a man who has spent four centuries removing himself from his own
// sentences" (RI-DLG06 §B row 1). Zero contractions and zero exclamation marks in that file are
// not the corpus-wide undershoot this gate was built to find. They are the characterisation.
//
// Without an exemption the gate tells the next writer to put contractions and exclamation marks
// into the game's Dagoth Ur conversation, and the writer who does as it says makes the corpus
// worse while turning a warning green. That is precisely the failure the round-2 builder recorded
// twice — a metric that charges a file for the fix — arriving from the opposite direction.
//
// THE LINE, and it is the whole design:
//   * Only the REGISTER-DEPENDENT bars may be exempted — questions, exclamations, contractions,
//     andopen. A formal speaker really does not contract or exclaim, and that is a defensible
//     authorial choice a file may declare.
//   * `sting`, `fragopen` and every tic are NEVER exemptible. They are the round's actual finding.
//     No register note justifies appending an interpretive clause to a fact, and if this hatch
//     could reach them it would become the way the finding gets undone one file at a time.
//   * The declaration must be IN THE FILE, machine-readable, and carry a reason per metric. An
//     exemption nobody can read is indistinguishable from a bug.
//   * Exempted metrics are still measured, still printed, and counted separately in the summary,
//     so the escape hatch is visible in the same output as the regressions rather than silent.
export const EXEMPTIBLE = new Set(['questions', 'exclamations', 'contractions', 'andopen']);

let EXEMPT_INDEX = null;
function buildExemptIndex(root = ROOT) {
  const idx = new Map();
  for (const dir of ['game/data/dialogue', 'game/data/books', 'game/data/quests']) {
    for (const f of walk(path.join(root, dir))) {
      const d = readJSON(f); if (!d) continue;
      const dec = d.prose_register_exemption;
      if (dec && typeof dec === 'object') idx.set(path.relative(root, f), dec);
    }
  }
  return idx;
}
export function exemptionsFor(relFile, root = ROOT) {
  if (!EXEMPT_INDEX) EXEMPT_INDEX = buildExemptIndex(root);
  const dec = EXEMPT_INDEX.get(relFile) || {};
  const out = {};
  for (const [k, why] of Object.entries(dec)) {
    if (EXEMPTIBLE.has(k) && typeof why === 'string' && why.trim().length >= 20) out[k] = why.trim();
  }
  return out;
}

function judge(bar, rate, fileWords) {
  // returns null when fine, else a short reason
  if (!bar) return null;
  const enoughToMiss = !fileWords || (bar.target * fileWords) / 1e4 >= MIN_EXPECTED;
  if (bar.kind === 'floor') return enoughToMiss && rate < bar.floor ? `${rate.toFixed(1)} < floor ${bar.floor.toFixed(1)} (reference ${bar.target.toFixed(1)})` : null;
  if (bar.kind === 'cap') return rate > bar.ceiling ? `${rate.toFixed(1)} > ceiling ${bar.ceiling.toFixed(1)} (reference ${bar.target.toFixed(1)})` : null;
  if (bar.kind === 'band') {
    if (rate > bar.hi) return `${rate.toFixed(1)} > band top ${bar.hi.toFixed(1)} — overshoot (reference ${bar.target.toFixed(1)})`;
    if (enoughToMiss && rate < bar.lo) return `${rate.toFixed(1)} < band floor ${bar.lo.toFixed(1)} — undershoot (reference ${bar.target.toFixed(1)})`;
    return null;
  }
  return null;
}

// ------------------------------------------------------------------ self-test
// Two halves, and the second is the one that is usually missing. A probe that cannot fail is worse
// than no probe (AGENT-PROTOCOL) — so every rule is fed a passage that violates exactly it, AND a
// passage that is clean, and both directions are asserted.
function selfTest() {
  let bad = 0;
  const t = (cond, msg) => { console.log(`  ${cond ? 'ok  ' : 'FAIL'}  ${msg}`); if (!cond) bad++; };
  console.log('check-prose --self-test');

  // --- primitives: red on the defect ---
  t(countSting('The road runs east. Which is the long way.') === 1, 'sting: red on a `Which` fragment close');
  t(countSting('He keeps the ledger, which is how the count was found.') === 1, 'sting: red on a promoted trailing clause');
  t(countSting('They came at dawn, and that is the whole of it.') === 1, 'sting: red on a trailing verdict clause');
  t(countSting('The road runs east. Take the second bridge.') === 0, 'sting: QUIET on a flat directions line');
  t(countSting('He is a bookworm. Try a bookseller.') === 0, 'sting: QUIET on real reference prose');
  t(countSting('It is white and wet. What more can I tell you?') === 0, 'sting: QUIET on a flat reference line that ends in a question');

  // the falsification, asserted so nobody silently re-gates it
  t(countEpigramEcho('That is not a mistake. A mistake happens once.') === 1, 'epigram-echo: detected');
  t(countSting('That is not a mistake. A mistake happens once.') === 0, 'epigram-echo is NOT counted as a sting (it is at parity with the reference)');

  // The three echo classes. The split exists because the composite reported 1.04x while one of its
  // parts was 0.28x and another 3.00x; each assertion below is a case the composite got wrong.
  t(epigramKind('That is not a mistake. A mistake happens once.') === 'echo_statement', 'echo: a declarative recast is the epigram proper');
  t(epigramKind('She wants a hand who can count and cannot be leaned on. Can you count?') === 'echo_question', 'echo: a closing QUESTION that reuses a word is a speaker recruiting the player, not an epigram');
  t(epigramKind('Blackrose lost a blade and Thorn found one. Ask at Thorn hall.') === 'echo_direction', 'echo: a closing IMPERATIVE that reuses a word is a direction, not an epigram');
  t(epigramKind("They're opening the Ladder and the road is full. Don't walk that road alone.") === 'echo_direction', 'echo: a negative imperative is a direction too');
  t(epigramKind('He is a bookworm. Try a bookseller.') === '', 'echo: QUIET on real reference prose that repeats no content word');
  t(epigramKind('One line only.') === '', 'echo: a single sentence cannot close on an echo');
  t(epigramKind('The tolls are written in the book. The book goes to the Assize once a season and to the table every night.') === '', 'echo: a long closing sentence is not a closing epigram');

  t(countFragOpen('Which is deliberate. And which is not.') === 1, 'fragopen: counts a sentence-initial Which');
  t(countFragOpen('Which is it? Which one, citizen?') === 0, 'fragopen: QUIET on an interrogative Which — a character asking the player something is the fix, not the defect');
  t(countFragOpen('The cart, which is late, has the salt.') === 0, 'fragopen: QUIET on a mid-sentence relative clause');

  t(countAndOpen('And he left. But he came back. So we waited.') === 3, 'andopen: counts all three conjunction openers');
  t(countAndOpen('He left and came back.') === 0, 'andopen: QUIET mid-sentence');

  t(countContractions("It's grey and it doesn't keep.") === 2, 'contractions: counted');
  t(countContractions('It is grey and it does not keep.') === 0, 'contractions: QUIET when expanded');
  t(countQuestions('Are you well? Truly?') === 2 && countExclamations('Stop! Now!') === 2, 'questions and exclamations counted');

  t(countTics('Somebody told anybody who would listen.')['-body form'] === 2, 'tic: -body forms red');
  t(countTics('Not one of them would listen.')['-body form'] === undefined, 'tic: -body QUIET on a concrete actor');
  t(countTics('She was asked eleven times.')['filler eleven'] === 1, 'tic: filler eleven red on an uncountable');
  t(countTics('Struck off the roll eleven years ago.')['filler eleven'] === undefined, 'tic: filler eleven QUIET on a plot date the quests cross-reference eight times');
  t(countTics('Eleven boxes came up the river.')['filler eleven'] === undefined, 'tic: filler eleven QUIET on a countable the player can verify');
  t(countTics('That is why the gate is shut.')['"that is what/why/all"'] === 1, 'tic: house cadence red');

  // --- the gate itself, end to end, on synthetic corpora ---
  const defective = Array.from({ length: 40 }, (_, i) => ({
    id: 'd' + i, file: 'synthetic/defective.json',
    text: `The count was short again this season and the ledger was not corrected, which is how the matter came to the Court. Somebody has been asked eleven times and that is what she will not answer. Which is deliberate.`,
  }));
  // THE CLEAN CONTROL, and the first version of it was wrong in a way worth recording.
  // It was one line repeated forty times — a line that happened to carry an exclamation mark and a
  // conjunction opener, so at forty copies the fixture ran at 370 exclamations per 10k and tripped
  // the OVERSHOOT half of the very band it was meant to pass. A control has to be a distribution,
  // not a sample. This one is a spread of flat service dialogue in the reference's register:
  // directions, prices, a shopkeeper's stock, one person who is curious about you and one who is
  // alarmed. Nothing in it lands a punchline. It must trip nothing.
  const CLEAN_FIXTURE = [
    "He's a bookworm. Try a bookseller.",
    "It's white and wet. What more can I tell you?",
    "A miserable place, from what I've heard. Too cold for me.",
    'Nothing there but a big rock. I never saw the point of it.',
    "Are you well? You don't look it.",
    'Go east past the ford, then ask at the customs post.',
    'I sell rope, lamp oil and salt. Nothing on credit.',
    'Watch yourself out there!',
    'And who told you that?',
    'The muster is on the board. Copy it down before you go.',
    'The ferry runs at dawn and at dusk. Miss it and you walk.',
    'Ten drakes for the room. Twelve if you want the shutters mended.',
    'She keeps the ledger in the back room. Knock first.',
    'Bandits on the north road. Two of them were taken last week.',
    'My cousin works the kiln. He says the clay is going bad.',
    'Buy a lamp. It gets dark early down there.',
    'The Assize sits on the first of the month. Bring your papers.',
    'So you are the one they sent for the ledger.',
    'Salt, rope, oil. Nothing else.',
    'I have not been down there. My sister has, and she will not go again.',
    'Three days by cart, longer if the river is up.',
    'The smith is out at the ford until the seventh.',
    'Room and board, six drakes. The stable is extra.',
    'They took the roof off the granary last winter.',
    'Speak to the harbourmaster. He has the manifest.',
    'I have salt fish and hard bread. Take it or leave it.',
  ];
  const clean = Array.from({ length: 78 }, (_, i) => ({
    id: 'c' + i, file: 'synthetic/clean.json', text: CLEAN_FIXTURE[i % CLEAN_FIXTURE.length],
  }));

  const bars = loadBars();
  const dfile = [...byFile(defective)][0][1];
  const cfile = [...byFile(clean)][0][1];
  const reg = bars.registers.dialogue;
  const fails = (sc) => Object.entries(reg || {}).filter(([k, bar]) => judge(bar, sc.rates[k])).map(([k]) => k);

  const df = fails(dfile), cf = fails(cfile);
  t(df.length > 0, `the gate goes RED on prose with the defect (${df.join(', ') || 'none'})`);
  t(df.includes('sting') && df.includes('questions'), 'and names the sting and the missing questions specifically');
  t(Object.keys(dfile.tics).length >= 2, 'and the tic list fires on it');
  t(cf.length === 0, `the gate stays QUIET on prose without it (flagged: ${cf.join(', ') || 'nothing'})`);
  t(Object.keys(cfile.tics).length === 0, 'and finds no tics in it');

  // THE DECLARED-REGISTER EXEMPTION, and the assertions that keep it from becoming a blanket
  // escape hatch. The one that matters is the third: if this could waive `sting`, the round's
  // whole finding could be undone one declaration at a time.
  t(EXEMPTIBLE.has('contractions') && EXEMPTIBLE.has('exclamations') && EXEMPTIBLE.has('questions') && EXEMPTIBLE.has('andopen'),
    'exemption: the four register-dependent bars may be waived');
  t(!EXEMPTIBLE.has('sting') && !EXEMPTIBLE.has('fragopen'),
    'exemption: sting and fragopen may NEVER be waived — they are the round\'s finding, not a register choice');
  {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'prose-ex-'));
    fs.mkdirSync(path.join(tmp, 'game/data/dialogue'), { recursive: true });
    fs.writeFileSync(path.join(tmp, 'game/data/dialogue/d.json'), JSON.stringify({
      prose_register_exemption: {
        contractions: 'a four-hundred-year-old clerk who has removed himself from his own sentences',
        sting: 'this must be ignored, a register note cannot license a closing sting',
        andopen: 'too short',
      },
      topics: [],
    }));
    const got = exemptionsFor('game/data/dialogue/d.json', tmp);
    t(got.contractions && /four-hundred-year-old/.test(got.contractions), 'exemption: a declared reason on an exemptible bar is honoured');
    t(got.sting === undefined, 'exemption: a declaration on `sting` is IGNORED even when the file asks for it');
    t(got.andopen === undefined, 'exemption: a reason under twenty characters is not a reason and is refused');
    t(Object.keys(exemptionsFor('game/data/dialogue/absent.json', tmp)).length === 0, 'exemption: a file that declares nothing gets nothing');
    fs.rmSync(tmp, { recursive: true, force: true });
  }

  // a file below min_words must not be judged at all — one question mark in 200 words is not a fact
  t(bars.min_words >= 200, 'a minimum-length guard exists so a short file cannot swing a rate');

  console.log(bad ? `SELF-TEST FAILED (${bad})` : `self-test passed (all assertions, both directions)`);
  return bad ? 1 : 0;
}

function loadBars() {
  if (fs.existsSync(BARS_FILE)) return JSON.parse(fs.readFileSync(BARS_FILE, 'utf8'));
  return DEFAULT_BARS;
}

// ------------------------------------------------------------------ calibration
async function calibrate() {
  const { referenceCorpus } = await import('./prose/tic-detector.mjs');
  const ref = referenceCorpus();
  const ours = ourText();
  const old = loadBars();
  const out = { ...DEFAULT_BARS, calibrated: new Date().toISOString().slice(0, 10), registers: {} };

  for (const r of ['dialogue', 'books', 'journal']) {
    if (!ref[r]?.length || !ours[r]?.length) continue;
    const R = scoreDocs(ref[r]).rates;
    const O = scoreDocs(ours[r]).rates;
    // EVERY BAR IS A MULTIPLE OF THE REFERENCE, NOT A PERCENTILE OF OURS.
    //
    // The first version of this calibrator set caps at the 90th percentile of our own files. That
    // is a ratchet against future regression and nothing else: it declares the corpus acceptable
    // by definition on the day it is written, and the sting cap came out at 69.65 per 10k against
    // a reference of 2.00 — thirty-five times the thing it was supposed to be measuring, and red
    // on nothing. A bar derived from the corpus it judges cannot say the corpus is wrong.
    //
    // So the bars are fixed multiples of the measured reference rate. They are loose multiples —
    // 3x for the caps, a quarter for the floors — because the goal is a check that names the files
    // a reader would notice, not one that demands the reference's exact distribution. The `target`
    // column keeps the honest distance visible either way.
    const bars = {
      // A file where essentially nobody asks the player anything. GAP-PROSE-01.
      questions: { kind: 'floor', target: R.questions, ours: O.questions, floor: R.questions * 0.25 },
      // Both ends. Zero across 7,648 words was the defect; 34.7 against 21.3 in the swept
      // generator was the opposite defect, and the seam between them is worse than either.
      exclamations: { kind: 'band', target: R.exclamations, ours: O.exclamations, lo: R.exclamations * 0.25, hi: R.exclamations * 2 },
      // THE CAP TRACKS OUR OWN IMPROVEMENT, or the ratchet is not a ratchet.
      //
      // The bars above and below are pure multiples of the reference, and that was the right fix
      // for the vacuous percentile version — but it left the "refuse to loosen" guard with nothing
      // to bite on, because a reference-derived number never moves when OUR corpus moves. Measured
      // live: this round took the dialogue sting rate from 43.47 per 10k to 1.12, a 39x
      // improvement, and the ceiling sat at 6.00 throughout. A regression all the way back to 5.9
      // — five times our current rate — would have been invisible to the check built to catch it.
      //
      // So the sting cap, the one bar this whole round exists for, is now the tightest of:
      //   * the reference multiple (never looser than that), and
      //   * twice our current rate (so an improvement locks in with slack for one new file),
      // and is NEVER tighter than the reference rate itself — a corpus writing at Morrowind's own
      // rate must not be red, or the check is measuring taste rather than the gap.
      sting: { kind: 'cap', target: R.sting, ours: O.sting, ceiling: Math.max(R.sting, Math.min(Math.max(R.sting * 3, 6), O.sting * 2)) },
      // `Math.max(..., 1.5)` because the reference rate here is at or near zero in two registers,
      // and a cap of zero is not a bar — it is an assertion that one occurrence anywhere is a bug.
      fragopen: { kind: 'cap', target: R.fragopen, ours: O.fragopen, ceiling: Math.max(R.fragopen * 3, 1.5) },
      andopen: { kind: 'band', target: R.andopen, ours: O.andopen, lo: R.andopen * 0.25, hi: R.andopen * 2 },
      contractions: { kind: 'band', target: R.contractions, ours: O.contractions, lo: R.contractions * 0.15, hi: R.contractions * 1.25 },
    };
    // REFUSE TO LOOSEN. A ratchet that can be quietly reset by re-running the calibrator is not a
    // ratchet — it is a rubber stamp, and the next agent to regress the corpus would re-baseline
    // it away without noticing. Caps may only fall, floors may only rise. Bands are derived from
    // the reference alone and so do not move at all.
    const prev = old.registers?.[r];
    if (prev) {
      for (const [k, bar] of Object.entries(bars)) {
        const p = prev[k]; if (!p || p.kind !== bar.kind) continue;
        if (bar.kind === 'cap' && bar.ceiling > p.ceiling) { console.warn(`  refused to loosen ${r}.${k} ceiling ${p.ceiling.toFixed(2)} -> ${bar.ceiling.toFixed(2)}; keeping the tighter one`); bar.ceiling = p.ceiling; }
        if (bar.kind === 'floor' && bar.floor < p.floor) { console.warn(`  refused to loosen ${r}.${k} floor ${p.floor.toFixed(2)} -> ${bar.floor.toFixed(2)}; keeping the higher one`); bar.floor = p.floor; }
      }
    }
    out.registers[r] = bars;
    out.registers[r].reference_words = scoreDocs(ref[r]).words;
    // UNGATED BUT MEASURED. The composite epigram rate is kept for continuity with the round-2
    // finding; the three classes under it are what a reader should actually act on, because the
    // composite averages a class we are BELOW the reference on (the closing question) with one we
    // are well above (the closing direction) and reports the result as "at parity".
    out.registers[r].reported = {
      epigram_echo: R.epigram_echo,
      echo_statement: R.echo_statement,
      echo_question: R.echo_question,
      echo_direction: R.echo_direction,
    };
    out.registers[r].epigram_echo_note = `NOT GATED, AND THE COMPOSITE IS MISLEADING ON ITS OWN. ours ${O.epigram_echo.toFixed(2)} vs reference ${R.epigram_echo.toFixed(2)} per 10k = ${(O.epigram_echo / (R.epigram_echo || 1)).toFixed(2)}x. Split by what the closing sentence does: statement ${O.echo_statement.toFixed(2)} vs ${R.echo_statement.toFixed(2)} (${(O.echo_statement / (R.echo_statement || 1)).toFixed(2)}x) — the epigram proper, at parity, so it is not our tell; question ${O.echo_question.toFixed(2)} vs ${R.echo_question.toFixed(2)} (${(O.echo_question / (R.echo_question || 1)).toFixed(2)}x) — a speaker turning the line back on the player, which the reference does MORE than we do and which this round exists to add; direction ${O.echo_direction.toFixed(2)} vs ${R.echo_direction.toFixed(2)} (${(O.echo_direction / (R.echo_direction || 1)).toFixed(2)}x) — closing on "Ask at X", a real mild tell that a flattening pass makes worse if nobody is watching it.`;
  }
  fs.writeFileSync(BARS_FILE, JSON.stringify(out, null, 2) + '\n');
  console.log(`check-prose --calibrate: wrote ${path.relative(ROOT, BARS_FILE)}`);
  for (const [r, b] of Object.entries(out.registers)) {
    console.log(`  ${r}:`);
    for (const [k, bar] of Object.entries(b)) {
      // `!bar.kind` skips the sibling `reported` block, which is an object of measured reference
      // rates for the UNGATED echo classes and has no bar to print.
      if (typeof bar !== 'object' || !bar.kind) continue;
      const lim = bar.kind === 'cap' ? `ceiling ${bar.ceiling.toFixed(2)}` : bar.kind === 'floor' ? `floor ${bar.floor.toFixed(2)}` : `band ${bar.lo.toFixed(2)}–${bar.hi.toFixed(2)}`;
      console.log(`    ${k.padEnd(13)} ours ${bar.ours.toFixed(2).padStart(8)}  reference ${bar.target.toFixed(2).padStart(8)}  ${lim}`);
    }
  }
  return 0;
}

// ------------------------------------------------------------------ main
async function main() {
  const argv = process.argv.slice(2);
  if (argv.includes('--self-test')) return selfTest();
  if (argv.includes('--calibrate')) return calibrate();
  const verbose = argv.includes('--verbose');
  const strict = argv.includes('--strict');
  const only = argv.includes('--file') ? argv[argv.indexOf('--file') + 1] : null;

  const bars = loadBars();
  const ours = ourText();
  let regressions = 0;
  let exemptCount = 0;
  const lines = [];

  for (const r of ['dialogue', 'books', 'journal']) {
    const reg = bars.registers?.[r];
    const all = ours[r] || [];
    if (!all.length) continue;
    const total = scoreDocs(all);
    if (verbose || only) {
      lines.push(`\n${r}: ${total.docs} passages, ${total.words} words`);
      for (const [k, v] of Object.entries(total.rates)) {
        const bar = reg?.[k];
        // The ungated echo classes still carry a measured reference rate, recorded by --calibrate.
        // Printing the bare number for them was the whole problem: a reader cannot act on "3.25"
        // without knowing the reference is 1.08, and the composite that used to stand in its place
        // said 1.04x when one of its three parts was 0.28x and another 3.00x.
        const refd = reg?.reported?.[k];
        lines.push(`  ${k.padEnd(14)} ${v.toFixed(2).padStart(8)} /10k` + (bar
          ? `   reference ${bar.target.toFixed(2)}  (${(v / (bar.target || 1)).toFixed(2)}x)`
          : refd != null
            ? `   reference ${refd.toFixed(2)}  (${(v / (refd || 1)).toFixed(2)}x)  [reported, not gated]`
            : '   [reported, not gated]'));
      }
    }
    for (const [f, sc] of byFile(all)) {
      if (only && !f.includes(only)) continue;
      if (sc.words < (bars.min_words || 400)) continue;
      const ex = exemptionsFor(f);
      const bad = [];
      const exempted = [];
      for (const [k, bar] of Object.entries(reg || {})) {
        if (typeof bar !== 'object' || !bar.kind) continue;
        const why = judge(bar, sc.rates[k], sc.words);
        if (!why) continue;
        if (EXEMPTIBLE.has(k) && ex[k]) exempted.push(`${k} ${why}  — EXEMPT: ${ex[k]}`);
        else bad.push(`${k} ${why}`);
      }
      const ticList = Object.entries(sc.tics).map(([k, v]) => `${k} x${v}`);
      if (bad.length || ticList.length || exempted.length) {
        regressions += bad.length;
        exemptCount += exempted.length;
        lines.push(`  ${f}  (${sc.words} w)`);
        for (const b of bad) lines.push(`      ${b}`);
        for (const tl of ticList) lines.push(`      tic: ${tl}`);
        for (const e of exempted) lines.push(`      ${e}`);
      } else if (verbose) {
        lines.push(`  ok  ${f}  (${sc.words} w)`);
      }
      if (only) {
        lines.push(`      --- ${f} ---`);
        for (const [k, v] of Object.entries(sc.rates)) lines.push(`      ${k.padEnd(14)} ${v.toFixed(2)} /10k` + (reg?.[k] ? `   reference ${reg[k].target.toFixed(2)}` : ''));
      }
    }
  }

  // ---- COVERAGE: which player-facing JSON has prose the collector never reached? --------------
  // W1-05. `road-directions.json` kept 46 spoken lines at `routes[].answers[].x`, a shape
  // `ourText()` did not know, so `--file game/data/dialogue/road-directions.json` printed the whole
  // corpus and NOTHING about the file — not a silent pass, an invisible one. Adding the shape fixed
  // that file; this catches the next one. It compares words the collector took from each file
  // against a crude count of every string in it, and names any file where it reached almost none.
  const covered = new Map();
  for (const r of ['dialogue', 'books', 'journal']) {
    for (const d of ours[r] || []) covered.set(d.file, (covered.get(d.file) || 0) + words(d.text));
  }
  const uncovered = [];
  for (const dir of ['game/data/dialogue', 'game/data/books']) {
    for (const f of walk(path.join(ROOT, dir))) {
      const rel = path.relative(ROOT, f);
      const d = readJSON(f); if (!d) continue;
      // Count only strings under the keys a SPOKEN LINE is written at anywhere in this corpus.
      // Counting every string instead was the first draft and it named `speakers.json` and
      // `faction-reactions.json` — two specification documents whose word count is all provenance
      // notes. A coverage warning that fires on files with no prose in them is noise, and noise is
      // how a check stops being read; the point of this one is to be believable when it fires.
      const SPOKEN_KEY = new Set(['x', 'text', 'line', 'lines', 'say', 'greeting']);
      let raw = 0;
      const walkVal = (v, key) => {
        if (typeof v === 'string') { if (SPOKEN_KEY.has(key)) raw += words(v); return; }
        if (Array.isArray(v)) { for (const q of v) walkVal(q, key); return; }
        if (v && typeof v === 'object') { for (const [k, q] of Object.entries(v)) walkVal(q, k); }
      };
      walkVal(d, '');
      const got = covered.get(rel) || 0;
      if (raw >= 300 && got < raw * 0.25) uncovered.push({ file: rel, raw, got });
    }
  }
  if (uncovered.length) {
    console.warn(`check-prose: COVERAGE — ${uncovered.length} file(s) hold prose this gate cannot see.`);
    console.warn('  The collector knows a fixed set of JSON shapes. A file in an unknown shape is not');
    console.warn('  measured at all, which reads as a pass. Teach ourText() the shape, or say why not.');
    for (const u of uncovered) console.warn(`  ${u.file}  ~${u.raw} authored words, ${u.got} measured`);
  }

  if (regressions) {
    console.warn(`check-prose: WARNING — ${regressions} prose-voice regression(s) past the recorded ratchet.`);
    console.warn('  These are voice defects a reader finds in four lines and no metric in the corpus');
    console.warn('  used to catch. See tools/prose/prose-bars.json for what each bar is made of, and');
    console.warn('  `node tools/check-prose.mjs --file <path>` for one file\'s numbers.');
    if (exemptCount) console.warn(`  (plus ${exemptCount} bar(s) waived by a declared register exemption, listed below and NOT counted above.)`);
    console.warn(lines.join('\n'));
    if (strict) { console.error('check-prose: --strict'); return 1; }
    return 0;
  }
  if (exemptCount) console.log(`check-prose: ${exemptCount} bar(s) waived by a declared register exemption.`);
  if (verbose || only) console.log(lines.join('\n'));
  console.log(`check-prose: ${Object.keys(bars.registers || {}).length} register(s) inside the recorded ratchet.`);
  return 0;
}

// Only run when executed directly. The metric functions above are exported so other tools (and
// the pack builder) can reuse them; importing this file must not run the gate and call exit().
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(await main());
}
