#!/usr/bin/env node
// publish-game.mjs — put the playable game on the web, so playing it is a link and not a clone.
//
// The owner asked how they play this on a phone. The honest answer was "you can't" — `./play.sh`
// serves from a laptop, and the only thing on the web was the blog. GitHub Pages serves this repo's
// `docs/` directory and the game lives in `game/`, so the game was never published at all.
//
// This copies `game/` to `docs/play/`. That is a mirror, and mirrors are the defect this project
// has now found four times — two soul ledgers, `magic.gold`, a gold write bypassing its setter —
// every one of them a second copy of a value with one writer and no reader in common. So this one
// is built the way the souls reconciliation was: **generated, never edited, and checked.**
//
//   node tools/publish-game.mjs           # regenerate docs/play/ from game/
//   node tools/publish-game.mjs --check   # exit 1 if they differ, naming the files
//
// `game/` is the only source. Nothing should ever be edited under `docs/play/`; the check exists so
// that if somebody does, it is loud rather than silent.
import { readdirSync, statSync, mkdirSync, copyFileSync, rmSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const SRC = join(ROOT, 'game');
const DST = join(ROOT, 'docs', 'play');

// Things the game does not need in a browser. `README.md` is developer prose; anything under a
// `node_modules` is not ours to ship. Keep this list short — a copy that quietly omits something
// the game fetches at runtime is a page that half-loads, which is worse than a big directory.
const SKIP = new Set(['node_modules', '.DS_Store']);

/** Every file under a directory, repo-relative, sorted so two runs agree. */
function walk(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir).sort()) {
    if (SKIP.has(name)) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out); else out.push(p);
  }
  return out;
}

const sha = (p) => createHash('sha256').update(readFileSync(p)).digest('hex');

const files = walk(SRC);
const check = process.argv.includes('--check');

if (check) {
  const missing = [], differ = [];
  for (const f of files) {
    const rel = relative(SRC, f);
    const target = join(DST, rel);
    if (!existsSync(target)) { missing.push(rel); continue; }
    if (sha(f) !== sha(target)) differ.push(rel);
  }
  // Also the other direction: a file under docs/play with no source is something somebody added by
  // hand, which is exactly what must not happen to a generated tree.
  // The marker this tool writes is the one file under docs/play with no source, by design.
  const orphans = walk(DST).map(f => relative(DST, f))
    .filter(rel => rel !== 'GENERATED-DO-NOT-EDIT.txt' && !existsSync(join(SRC, rel)));

  if (missing.length || differ.length || orphans.length) {
    console.error(`publish-game --check: docs/play/ does not match game/.`);
    for (const r of missing.slice(0, 10)) console.error(`  missing:  ${r}`);
    for (const r of differ.slice(0, 10)) console.error(`  differs:  ${r}`);
    for (const r of orphans.slice(0, 10)) console.error(`  orphaned: ${r}   (edited by hand? nothing under docs/play/ is a source)`);
    const more = missing.length + differ.length + orphans.length - 30;
    if (more > 0) console.error(`  … and ${more} more`);
    console.error(`\n  Run \`node tools/publish-game.mjs\`. game/ is the only source.`);
    process.exit(1);
  }
  console.log(`publish-game --check: docs/play/ matches game/ (${files.length} files).`);
  process.exit(0);
}

if (existsSync(DST)) rmSync(DST, { recursive: true });
let bytes = 0;
for (const f of files) {
  const target = join(DST, relative(SRC, f));
  mkdirSync(dirname(target), { recursive: true });
  copyFileSync(f, target);
  bytes += statSync(f).size;
}

// A marker, so anyone who opens the directory knows it is not a place to edit.
writeFileSync(join(DST, 'GENERATED-DO-NOT-EDIT.txt'),
  `Generated by tools/publish-game.mjs from game/.\n\nEvery file here is a copy. Edit game/ and re-run the tool; \`--check\` fails if these\ndrift apart, and the pre-commit hook runs it. Nothing under docs/play/ is a source.\n`);

console.log(`publish-game: ${files.length} files, ${(bytes / 1048576).toFixed(1)} MB -> docs/play/`);
console.log(`publish-game: playable at <pages-url>/play/index.html once pushed.`);
